// MP-08/MP-10/MP-11: upstream baseline only; no Selkies product authority.
import {profileOwnedCpu} from './drill-profile.mjs';
import {tmpdir} from 'node:os';
import {createServer} from 'node:http';import {createRequire} from 'node:module';
import {readFile,writeFile,mkdir,mkdtemp,chmod,chown,rm} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';import path from 'node:path';
import {fixture} from './drill-fixtures.mjs';import {distribution} from './drill-metrics.mjs';import {MetricsWorker} from './drill-metrics-worker.mjs';
import {CpuSampler,cpuSpan} from './drill-cpu.mjs';import {launchOwned,checkChild,stopGroup} from './drill-owned-process.mjs';import {sourceIdentity} from './source-identity.mjs';
const [output,tools,python]=process.argv.slice(2);if(![output,tools,python].every(p=>p&&path.isAbsolute(p)))throw Error('MP-10: absolute output/tools/Selkies2 Python required');
const require=createRequire(path.join(tools,'package.json')),{chromium}=require('playwright-core'),{PNG}=require('pngjs');
const here=path.dirname(fileURLToPath(import.meta.url)),root=await mkdtemp(path.join(tmpdir(),'chariox-display-baseline-'));await chmod(root,0o755);await mkdir(output,{recursive:true});
const shortTmp=await mkdtemp(path.join(tmpdir(),'cx-'));await chmod(shortTmp,0o700);await chown(shortTmp,65534,65534);
const legacy=process.env.MD_BASELINE==='legacy';
const receipt={item:'MP-08/MP-10/MP-11',...await sourceIdentity(),backend:legacy?'Selkies legacy 17a3d5a GStreamer/WebRTC x264enc':'Selkies 2.0.0 pixelflux/WebSocket x264',geometry:[1920,1080],dpr:1,gpu_requested:process.env.MD_BASELINE_GPU==='1'||process.env.MD_BASELINE_ENCODER==='vah264enc',budget_bps:Number(process.env.MD_BITRATE||8000000),workload:process.env.MD_WORKLOAD||'docs',status:'RED',state_root:root,short_tmp_root:shortTmp,cleanup:[],samples:[]};
const owned=[];let browser,sourceBrowser,server,pipelineLog='',page,stopProfile;const metrics=new MetricsWorker(tools),cpu=new CpuSampler({root,viewerRoot:path.join(root,'viewer')});cpu.start();let interrupted=false;
for(const s of ['SIGINT','SIGTERM'])process.on(s,()=>{interrupted=true;void browser?.close().catch(()=>{});void sourceBrowser?.close().catch(()=>{});});
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label,ms=20000){const end=Date.now()+ms;while(Date.now()<end){if(interrupted)throw Error('MP-10 interrupted');const value=await fn();if(value)return value;await pause(20)}throw Error('MP-10 timeout '+label);}
async function launch(command,args,options={}){const child=await launchOwned(command,args,{detached:true,stdio:'ignore',...options});owned.push(child);await cpu.track(child.pid,options.cpuRole??'pipeline');return child;}
async function browserAt(profile,headed,args=[]){await mkdir(profile);await chown(profile,65534,65534);const child=await launch(process.env.MD_CHROME||'/usr/bin/google-chrome',[`--user-data-dir=${profile}`,'--remote-debugging-address=127.0.0.1','--remote-debugging-port=0','--no-first-run','--disable-background-networking','--disable-dev-shm-usage','--force-device-scale-factor=1',...(!headed?['--headless=new','--disable-features=WebRtcHideLocalIpsWithMdns','--force-webrtc-ip-handling-policy=default_public_and_private_interfaces']:[]),...args],{cpuRole:headed?'source':'viewer',uid:65534,gid:65534,env:{PATH:'/usr/bin:/bin',HOME:profile,...(headed?{DISPLAY:receipt.display}:{}),TMPDIR:shortTmp}});const port=await until(async()=>{checkChild(child,'Chromium');try{return Number((await readFile(path.join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0])}catch{}},'Chromium');return chromium.connectOverCDP('http://127.0.0.1:'+port);}
try{
 const text=await readFile(path.resolve(here,'../../docs/MULTIDOMAIN_KERNEL_BROWSER.md'),'utf8');
 server=createServer(async(req,res)=>{const page=fixture(new URL(req.url,'http://localhost').pathname,'http://localhost',text);if(page){res.setHeader('content-type','text/html');res.end(page)}else if(req.url==='/viewer'){res.setHeader('content-type','text/html');res.end(await readFile(path.join(here,legacy?'baseline-legacy-viewer.html':'baseline-viewer.html')))}else if(['/baseline-packet.mjs','/motion-samples.mjs','/baseline-input.mjs'].includes(req.url)){res.setHeader('content-type','text/javascript');res.end(await readFile(path.join(here,req.url.slice(1))))}else res.end('ok')});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
 const xvfb=await launch('/usr/bin/Xvfb',['-displayfd','3','-screen','0','1920x1080x24','-nolisten','tcp','-ac'],{stdio:['ignore','ignore','ignore','pipe']});let number='';xvfb.stdio[3].on('data',b=>number+=b);await until(()=>number.includes('\n'),'Xvfb');receipt.display=':'+number.trim();
 sourceBrowser=await browserAt(path.join(root,'source'),true,['--window-position=0,0','--window-size=1921,1081','--kiosk',`--app=${origin}/${receipt.workload}`]);const source=sourceBrowser.contexts()[0].pages()[0];await source.waitForSelector('#step');receipt.source_geometry=await source.evaluate(()=>({width:innerWidth,height:innerHeight,dpr:devicePixelRatio}));const cdp=await source.context().newCDPSession(source);await cdp.send('Emulation.setDeviceMetricsOverride',{width:1920,height:1080,deviceScaleFactor:1,mobile:false});await source.waitForFunction(()=>innerWidth===1920&&innerHeight===1080);await cdp.send('Page.bringToFront');await source.screenshot();
 const reservation=createServer();await new Promise(r=>reservation.listen(0,'127.0.0.1',r));const port=reservation.address().port;await new Promise(r=>reservation.close(r));
 const runtime=path.join(root,'runtime');await mkdir(runtime,{mode:0o700});
 await writeFile(path.join(runtime,'rtc.json'),JSON.stringify({iceServers:[]}));
 const pipelineArgs=legacy?['-m','selkies_gstreamer','--addr=127.0.0.1',`--port=${port}`,`--json_config=${runtime}/config.json`,`--rtc_config_json=${runtime}/rtc.json`,'--encoder='+ (process.env.MD_BASELINE_ENCODER||'x264enc'),'--framerate=60',`--video_bitrate=${receipt.budget_bps/1000}`,'--enable_resize=false','--enable_clipboard=false','--enable_https=false','--enable_basic_auth=false','--enable_metrics_http=false','--audio_channels=2','--keyframe_distance=1']:['-m','selkies',`--allowed-origins=${origin}`,'--addr=127.0.0.1',`--port=${port}`,'--mode=websockets','--encoder=h264enc','--use-cpu='+ (process.env.MD_BASELINE_GPU==='1'?'false|locked':'true|locked'),'--framerate=60-60','--rate-control-mode=cbr',`--video-bitrate=${receipt.budget_bps/1000}-${receipt.budget_bps/1000}`,'--manual-resolution=true|locked','--manual-width=1920','--manual-height=1080','--enable-resize=false|locked','--audio-enabled=false|locked','--microphone-enabled=false|locked','--gamepad-enabled=false|locked','--webcam-enabled=false|locked','--enable-clipboard=false','--enable-basic-auth=false'];
 const pipeline=await launch(python,pipelineArgs,{env:{PATH:'/usr/bin:/bin',HOME:root,DISPLAY:receipt.display,XDG_RUNTIME_DIR:runtime},stdio:['ignore','pipe','pipe']});pipeline.stderr.on('data',b=>pipelineLog+=b);pipeline.stdout.on('data',b=>pipelineLog+=b);
 await until(async()=>{checkChild(pipeline,'Selkies');try{return (await fetch('http://127.0.0.1:'+port+(legacy?'/health':''))).ok}catch{}},'Selkies');
 browser=await browserAt(path.join(root,'viewer'),false,['about:blank']);page=await browser.contexts()[0].newPage();await page.goto(origin+'/viewer');await page.evaluate(({url,bitrate,gpu})=>mdAttach({url,bitrate,gpu}),{url:'ws://127.0.0.1:'+port+(legacy?'/ws':'/api/websockets'),bitrate:receipt.budget_bps,gpu:process.env.MD_BASELINE_GPU==='1'});await until(()=>page.evaluate(()=>{if(mdErrors.length)throw Error(mdErrors[0]);return mdPresentations.length}),'first pixel',30000);
 receipt.codec=await page.evaluate(()=>mdCodec);
 const probePng=PNG.sync.read(await source.screenshot()),row=28;let left=null,start=null;
 for(let x=1560;x<1920;x++){const at=(row*1920+x)*4,black=probePng.data[at]<5&&probePng.data[at+1]<5&&probePng.data[at+2]<5;if(black&&start===null)start=x;if(!black&&start!==null){if(x-start===40)left=start;start=null;}}
 if(left===null)throw Error('MP-10 cannot bind source pixel probe');receipt.probe_pixel_left=left;await page.evaluate(left=>window.mdProbeLeft=left,left);

 async function pair(name){const expected=await source.screenshot({type:'png'}),snapshot=await page.evaluate(()=>mdSnapshot()),actual=Buffer.from(snapshot.png.split(',')[1],'base64'),{diff,...result}=await metrics.compare(expected,actual);await writeFile(path.join(output,name+'-source.png'),expected);await writeFile(path.join(output,name+'-viewer.png'),actual);if(diff)await writeFile(path.join(output,name+'-diff.png'),diff);return {...result,presentation:snapshot.presentation};}
 const idleBefore=await cpu.sample(),idleStats=await page.evaluate(()=>mdStats());await pause(2000);receipt.idle_cpu=cpuSpan(idleBefore,await cpu.sample());const idleAfter=await page.evaluate(()=>mdStats());receipt.idle_video_mbps=(legacy?idleAfter.bytes-idleStats.bytes:idleAfter.frames.slice(idleStats.frames.length).reduce((n,f)=>n+f.bytes,0))*8/receipt.idle_cpu.duration_ms/1000;receipt.settled=await pair('settled');
 if(receipt.workload!=='docs'){
  stopProfile=await profileOwnedCpu(await cpu.sample(),output);
  const sourceScrollBefore=await source.evaluate(()=>scrollY);const start=await cpu.sample(),before=await page.evaluate(async()=>{const s=await mdStats();return {bytes:s.bytes,frames:s.frames.length,presentations:s.presentations.length}}),at=performance.now(),pairs=[];let wheel;
  if(receipt.workload==='wheel30'||receipt.workload==='wheel60')await page.evaluate(hz=>{window.mdWheel=setInterval(()=>mdInput({kind:'scroll',x:700,y:600,delta_y:120}),1000/hz)},receipt.workload==='wheel60'?60:30);else await page.evaluate(()=>mdInput({kind:'click',x:60,y:88}));
  while(performance.now()-at<10000){if(pairs.length<2&&performance.now()-at>(pairs.length+1)*1000)pairs.push(await pair('moving-live-'+pairs.length));await pause(33);}
  const duration=performance.now()-at,after=await page.evaluate(()=>mdStats());receipt.motion={source_scroll:{before:sourceScrollBefore,after:await source.evaluate(()=>scrollY)},effective_fps:(after.presentations.length-before.presentations)*1000/duration,effective_content_fps:after.presentations.slice(before.presentations).filter(p=>p.content_changed).length*1000/duration,event_mbps:(legacy?after.bytes-before.bytes:after.frames.slice(before.frames).reduce((a,b)=>a+b.bytes,0))*8/duration/1000,application_mbps:(after.bytes-before.bytes)*8/duration/1000,live_pairs:pairs,cpu:cpuSpan(start,await cpu.sample())};
  if(receipt.workload==='wheel30'||receipt.workload==='wheel60')await page.evaluate(()=>clearInterval(mdWheel));else await page.evaluate(()=>mdInput({kind:'click',x:60,y:88}));await pause(1000);receipt.motion.settled_fidelity=await pair('motion-settled');await stopProfile();stopProfile=null;
 }
 const clicks=[],begin=await cpu.sample();for(let i=1;i<=20;i++){
  const probe=await page.evaluate(async expected=>{const at=performance.timeOrigin+performance.now();mdInput({kind:'click',x:1830,y:28});const deadline=at+10000;while(mdPresentation?.step!==expected){if(mdErrors.length)throw Error(mdErrors[0]);if(performance.timeOrigin+performance.now()>deadline)throw Error('pixel acknowledgement timeout');await new Promise(r=>requestAnimationFrame(r));}return {latency_ms:mdPresentation.presented_ms-at,step:mdPresentation.step};},i);clicks.push(probe.latency_ms);
 }
 receipt.latency=distribution(clicks);receipt.click_cpu=cpuSpan(begin,await cpu.sample());
 const typeCpu=await cpu.sample();const types=[];for(let i=21;i<=40;i++){
  await page.evaluate(()=>mdInput({kind:'click',x:1750,y:28}));await pause(100);
  types.push(await page.evaluate(async expected=>{const at=performance.timeOrigin+performance.now();mdInput({kind:'text',text:'a'});const deadline=at+10000;while(mdPresentation?.step!==expected){if(mdErrors.length)throw Error(mdErrors[0]);if(performance.timeOrigin+performance.now()>deadline)throw Error('typing pixel acknowledgement timeout');await new Promise(r=>requestAnimationFrame(r));}return mdPresentation.presented_ms-at;},i&31));
 }
 receipt.type_latency=distribution(types);receipt.type_cpu=cpuSpan(typeCpu,await cpu.sample());receipt.status='PASS_BASELINE_COMPONENT';
}catch(error){receipt.error=error.message;receipt.viewer_diagnostic=await page?.evaluate(async()=>({packets:mdPacketMetadata,controls:mdControlKinds,errors:mdErrors,ice_state:window.mdPeer?.iceConnectionState,connection_state:window.mdPeer?.connectionState,signaling_state:window.mdPeer?.signalingState,video:document.querySelector('video')?{readyState:document.querySelector('video').readyState,paused:document.querySelector('video').paused,width:document.querySelector('video').videoWidth}:null,stats:window.mdPeer?[...(await mdPeer.getStats()).values()].filter(r=>['inbound-rtp','transport'].includes(r.type)).map(r=>({type:r.type,kind:r.kind,bytesReceived:r.bytesReceived,packetsReceived:r.packetsReceived,framesReceived:r.framesReceived,framesDecoded:r.framesDecoded,dtlsState:r.dtlsState})):null})).catch(()=>null);process.exitCode=interrupted?130:1;}
finally{
 await stopProfile?.().catch(e=>{receipt.cleanup.push(e.name);process.exitCode=1});await writeFile(path.join(output,'server.log'),pipelineLog);
 await browser?.close().catch(()=>{});await sourceBrowser?.close().catch(()=>{});for(const c of owned.reverse())try{await stopGroup(c)}catch(e){receipt.cleanup.push(e.message);process.exitCode=1;}
 await metrics.close();await cpu.close();receipt.cpu_samples=cpu.samples;await new Promise(r=>server?server.close(r):r());
 const remaining=[];for(const name of await (await import('node:fs/promises')).readdir('/proc'))if(/^\d+$/.test(name))try{if((await readFile('/proc/'+name+'/cmdline','utf8')).includes(root))remaining.push(Number(name));}catch{}
 if(remaining.length){receipt.cleanup.push('RED owned processes remain');receipt.remaining_pids=remaining;process.exitCode=1;}else{await rm(root,{recursive:true});await rm(shortTmp,{recursive:true});receipt.cleanup.push('owned processes absent; exact disposable state removed');}
 receipt.limits='Software canvas/rAF proxy. Identical latest-source/live-viewer PNG comparison includes temporal drift. Pipeline includes Xvfb, pixelflux/x264 and server; local baseline has no relay. Exited CPU counters retain sampled high-water values. No GPU or hosted acceptance.';
 receipt.exit_code=process.exitCode||0;await writeFile(path.join(output,'results.json'),JSON.stringify(receipt,null,2));console.log(JSON.stringify({item:receipt.item,status:receipt.status,error:receipt.error,output}));
}
