[package]
name = "arroba-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
portable-pty = "0.8.1"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread", "signal"] }

[lib]
name = "arroba_daemon"
path = "src/lib.rs"

[[bin]]
name = "arroba-daemon"
path = "src/main.rs"
