[package]
name = "arroba-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
portable-pty = "0.8.1"
rand = "0.8"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["io-util", "macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
wait-timeout = "0.2.0"
libc = "0.2.172"

[lib]
name = "arroba_daemon"
path = "src/lib.rs"

[[bin]]
name = "arroba-daemon"
path = "src/main.rs"

[[bin]]
name = "arroba-cli"
path = "src/bin/arroba-cli.rs"

[[bin]]
name = "arroba-cli-rust"
path = "src/bin/arroba-cli-rust.rs"
