pub mod agent;
pub mod app;
pub mod artifacts;
pub mod attachment;
pub mod capability;
pub mod config;
pub mod connector;
pub mod credential;
pub(crate) mod debug_trace;
pub(crate) mod durable_snapshot;
pub mod durable_state;
pub(crate) mod env_lock;
pub mod error;
pub mod execution_lease;
pub mod extension;
pub(crate) mod git_observer;
pub mod history;
pub mod history_archive;
pub mod io;
pub mod local;
pub mod logging;
pub mod mcp;
pub mod prompt_transcript;
pub mod provider;
pub mod pty;
pub(crate) mod prompt_assembly;
pub mod runtime;
pub mod runtime_transport;
pub mod scheduler;
pub mod script;
pub mod secret;
pub mod session;
pub mod session_history_page;
pub mod skill;
pub mod slice;
pub mod terminal;
pub mod transport;
pub(crate) mod workspace_live_sync_ignore;

pub use app::DaemonApp;
pub use config::DaemonConfig;
pub use error::DaemonError;

#[cfg(test)]
mod lib_tests;
