Section "ServerFlags"
    Option "AutoAddDevices" "false"
    Option "DontVTSwitch" "true"
EndSection
Section "Device"
    Identifier "chariox-dummy"
    Driver "dummy"
    VideoRam 131072
EndSection
Section "Monitor"
    Identifier "chariox-monitor"
    HorizSync 5.0-200.0
    VertRefresh 5.0-200.0
    Modeline "1280x800" 83.50 1280 1352 1480 1680 800 803 809 831 -hsync +vsync
    Modeline "1024x768" 65.00 1024 1048 1184 1344 768 771 777 806 -hsync -vsync
EndSection
Section "Screen"
    Identifier "chariox-screen"
    Device "chariox-dummy"
    Monitor "chariox-monitor"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "1280x800" "1024x768"
        Virtual 4096 4096
    EndSubSection
EndSection
Section "ServerLayout"
    Identifier "chariox-layout"
    Screen "chariox-screen"
EndSection
