mod api;
mod client;
mod harness;
mod ipc;
pub(crate) mod provider_requests;
#[cfg(test)]
pub(crate) mod test_support;

pub use api::{
    deployment_credential_enrollment_interaction_id,
    deployment_credential_enrollment_service_subject,
};
pub use api::{
    AbortMetaagentTaskRequest, AcceptCloudSessionInviteRequest, AckMetaagentEventsRequest,
    AckWorkflowTurnRequest, AcknowledgeAgentOutputSeenRequest, AddWorkflowEdgeRequest,
    AddWorkflowNodeRequest, AddWorkflowRegistryEntryFromWorkflowRequest,
    AddWorkflowRegistryEntryRequest, AgentSubstituteAction, AgentUtilityInput, AgentUtilityKind,
    AgentUtilityOutput, AgentUtilityResult, AliasAgentRequest, AliasSessionRequest,
    AliasWorkflowEndpointRequest, AliasWorkflowRequest, AppendNativeProviderOutputBatchItem,
    AppendNativeProviderOutputBatchRequest, AppendNativeProviderOutputRequest,
    ApplyWorkflowCodeArtifactRequest, ApplyWorkflowCodeRequest, ApplyWorkflowDesignOpRequest,
    ApproveRemoteMachineRequest, ArchiveProjectRequest, ArmDeploymentCredentialEnrollmentRequest,
    AttachToSessionRequest, AttachWorkspaceLinkRequest, BatchOperationFailure,
    BindWorkflowEndpointRequest, BindWorkflowPublicationDeploymentRequest,
    BrowseEventGeneratorCategoryRequest, BrowseEventGeneratorEventsRequest,
    CancelActivePromptRequest, CancelAgentPromptScheduleRequest, CancelQueuedPromptRequest,
    CancelWorkflowRunRequest, CaptureScreenshotCapabilityRequest, ClearWorkflowPromptQueueRequest,
    CloudCollaborator, CloudRelayLoginPoll, CloudRelayLoginPollStatus, CloudRelayLoginStart,
    CloudRelayProfile, CloudRelayRuntimeToken, CloudRelayStatusRequest, CloudSessionInvite,
    CloudSessionInviteAcceptance, CloudSessionInviteDetails, CloudSessionMember,
    CommitAndPushWorkspaceChangesRequest, CommitWorkspaceChangesRequest, CompletePromptRequest,
    ConfigureRelayRequest, ConnectCloudRelayRequest, ControlWorkflowPublicationRuntimeRequest,
    CreateAgentPromptScheduleRequest, CreateCloudSessionInviteRequest, CreatePairingInviteRequest,
    CreateSessionInviteRequest, CreateSliceBackupRequest, CreateSliceRequest,
    CreateTerminalPairingLinkRequest, CreateWorkflowCodeArtifactRequest,
    CreateWorkflowEndpointRequest, CreateWorkflowEventBindingRequest,
    CreateWorkflowPromptQueueRequest, CreateWorkflowPublicationRequest, CreateWorkflowRequest,
    CreateWorkflowScheduleRequest, CreateWorkflowWatchdogRequest, CreateWorkspaceDirectoryRequest,
    CreateWorkspaceLinkRequest, CreateWorkspacePullRequestRequest, CreateWorkspaceWorktreeRequest,
    CredentialEnrollmentCallback, CredentialEnrollmentInteractionStatus, CycleAgentFocusRequest,
    DeleteCredentialSecretRequest, DeleteKernelRequest, DeleteProjectRequest, DeleteSessionRequest,
    DeleteWorkflowCodeArtifactRequest, DeleteWorkflowRegistryEntryRequest,
    DeleteWorkspaceWorktreeRequest, DestroyAgentRequest, DetachFromSessionRequest,
    DetachWorkspaceLinkRequest, DisableWorkflowPublicationRequest, EditFileCapabilityRequest,
    EndSessionRequest, EventCatalogCategory, EventCatalogFacet, EventCatalogFacetValue,
    EventConnection, EventConnectionAuthorization, EventConnectionStatus, EventDeliveryStatus,
    EventGeneratorAuthorizationFlow, EventGeneratorCatalogDetail, EventGeneratorCatalogPage,
    EventGeneratorCatalogSummary, EventGeneratorEventDefinition, EventGeneratorEventPage,
    EventGeneratorParty, EventGeneratorResource, EventGeneratorResourcePage,
    ExportDebugBundleRequest, ExportWorkflowCodeArtifactRequest, ExportWorkflowCodePackageRequest,
    ExportWorkflowCodeSourceRequest, ExportWorkflowPublicationPackageRequest, ExtensionKind,
    ExternalProviderSessionCapabilities, ExternalProviderSessionPage,
    ExternalProviderSessionRecord, FocusAgentRequest, ForgetRemoteMachineRequest, ForkAgentRequest,
    GenerateWorkspaceCommitMessageRequest, GetConnectorAdapterRequest, GetConnectorRequest,
    GetCredentialRequest, GetCredentialVaultStatusRequest, GetDaemonHealthRequest,
    GetEnvironmentRequest, GetEventDeliveryStatusRequest, GetEventGeneratorCatalogLandingRequest,
    GetEventGeneratorDetailRequest, GetMcpServerRequest, GetMetaagentTurnBlobRequest,
    GetMetaagentTurnOverviewRequest, GetPromptInputHistoryRequest, GetProviderAuthStatusRequest,
    GetProviderCatalogRequest, GetProviderCommandCatalogsRequest, GetProviderRunRequest,
    GetScriptRequest, GetSessionHistoryBlobContentRequest, GetSessionHistoryOutlineRequest,
    GetSessionStateRequest, GetSkillRequest, GetSliceLogsRequest, GetTerminalCommandCatalogRequest,
    GetUserConfigRequest, GetUserConfigSchemaRequest, GetWaitingRoomPublicSnapshotRequest,
    GetWorkflowCodeArtifactRequest, GetWorkflowPublicationRequest, GetWorkflowRegistryEntryRequest,
    GetWorkflowRunRequest, GetWorkspaceFileContentRequest, GetWorkspaceGitOverviewRequest,
    GetWorkspaceLiveSyncStatusRequest, GrantAgentExtensionRequest,
    ImportExternalProviderAgentRequest, ImportExternalProviderSessionRequest,
    ImportMcpServersRequest, ImportProviderCapabilitiesRequest, ImportSkillsRequest,
    ImportSliceProviderAuthRequest, ImportWorkflowCodeArtifactRequest,
    ImportWorkflowCodePackageRequest, InspectGitCapabilityRequest, InstallMcpServerRequest,
    InstallSkillRequest, InvokeWorkflowEndpointRequest, IssueCloudRelayClientTokenRequest,
    JoinPairingInviteRequest, JoinSessionInviteRequest, JoinTerminalPairingLinkRequest,
    KernelClientConnection, LaunchProviderRunRequest, LaunchProviderRunsRequest, ListAgentsRequest,
    ListCloudCollaboratorsRequest, ListCloudSessionMembersRequest, ListConnectorAdaptersRequest,
    ListConnectorsRequest, ListCredentialsRequest, ListEnvironmentsRequest,
    ListEventGeneratorResourcesRequest, ListExternalProviderSessionsRequest,
    ListHomeExtensionAuditRequest, ListMcpServersRequest, ListMetaagentEventsRequest,
    ListPairedClientsRequest, ListProjectsRequest, ListProviderProcessesRequest,
    ListQueuedWorkflowPromptsRequest, ListRemoteMachineKernelsRequest, ListRemoteMachinesRequest,
    ListScriptsRequest, ListSessionMembersRequest, ListSessionsRequest, ListSkillsRequest,
    ListSliceAuditRequest, ListSlicesRequest, ListTerminalsRequest,
    ListWorkflowCodeArtifactsRequest, ListWorkflowEventBindingsRequest,
    ListWorkflowPromptQueuesRequest, ListWorkflowPublicationsRequest, ListWorkflowRegistryRequest,
    ListWorkflowRunsRequest, ListWorkflowSchedulesRequest, ListWorkflowWatchdogsRequest,
    ListWorkflowsRequest, ListWorkspaceFilesRequest, ListWorkspaceLinksRequest,
    ListWorkspaceWorktreesRequest, LoadWorkflowRegistryEntryRequest, LocalDaemonRequest,
    LocalDaemonResponse, LockCredentialVaultRequest, LogoutCloudRelayRequest,
    LogoutProviderRequest, ManageCredentialVaultRequest, MaterializeWorkflowPublicationRequest,
    MoveAgentToLocalRequest, MoveAgentToRemoteRequest, NativeProviderInteractionResolution,
    PairCloudRelayClientRequest, PairCloudRelayMachineRequest, PairedClientRecord,
    PairingInviteIntent, PairingInviteRecord, PairingJoinRecord, PauseMetaagentTaskRequest,
    PauseWorkflowRunRequest, PollCloudRelayLoginRequest, PollRuntimeNoticesRequest,
    PreviewWorkflowScheduleRequest, PromptBatchSubmissionResult, PromptInputHistoryEntry,
    PromptInputHistoryEntryKind, ProviderCapabilityImportDuplicate, ProviderCapabilityImportEntry,
    ProviderCapabilityImportReport, ProviderCapabilityImportSummary, ProviderRunBatchLaunchResult,
    PumpTerminalOutputRequest, PushWorkspaceBranchRequest, QueryRecallRequest,
    ReadDirectoryTreeCapabilityRequest, ReadFileCapabilityRequest, ReadMetaagentEventRequest,
    RecordPairedClientRequest, RecordPromptInputHistoryRequest,
    RefreshExternalProviderSessionsRequest, RegisterConnectorAdapterRequest,
    RegisterConnectorRequest, RegisterCredentialRequest, RegisterEnvironmentRequest,
    RegisterScriptRequest, RegisterWorkflowPublicationEndpointRequest, RelayStatus,
    RelayStatusRequest, RemoteMachineRecord, RemoteMachineTrustStatus,
    RemoveConnectorAdapterRequest, RemoveConnectorRequest, RemoveCredentialRequest,
    RemoveEnvironmentRequest, RemoveQueuedWorkflowPromptRequest, RemoveScriptRequest,
    RemoveSliceProviderAuthRequest, RemoveWorkflowEdgeRequest, RemoveWorkflowNodeRequest,
    RemoveWorkflowPromptQueueRequest, RemoveWorkflowScheduleRequest, RemoveWorkflowWatchdogRequest,
    RenameProjectRequest, RenameRemoteMachineRequest,
    RequestCredentialEnrollmentInteractionRequest, RequestNativeProviderInteractionRequest,
    ResizeTerminalRequest, ResolveKernelClientConnectionRequest, ResolveSessionRequest,
    ResolveWorkflowRequest, RespondToInteractionRequest, RestoreProjectRequest,
    ResumeMetaagentTaskRequest, ResumeWorkflowRunRequest, RevokeAgentExtensionRequest,
    RevokeCloudSessionInviteRequest, RevokePairedClientRequest, RevokeSessionInviteRequest,
    RunAgentUtilityRequest, RunShellCapabilityRequest, RunWorkflowCodeArtifactRequest,
    RunWorkflowCodeRequest, RunWorkflowRegistryEntryRequest, SearchEventGeneratorCatalogRequest,
    SearchMetaagentCommandsRequest, SearchRecallRequest, SearchWorkspaceDirectoriesRequest,
    SemanticRecallMatch, SemanticRecallSearchUtilityInput, SemanticSearchRecallMode,
    SemanticSearchRecallRequest, SendTerminalInputRequest, SessionHistoryOutlineAgent,
    SessionHistoryOutlineBlob, SessionHistoryOutlineCursor, SessionHistoryOutlineTurn,
    SessionHistoryOutlineTurnLifecycle, SessionInviteRecord, SetCredentialSecretRequest,
    SetSliceProviderAuthAliasRequest, SetUserConfigValueRequest,
    SetWorkflowEventBindingStatusRequest, SetWorkflowFlushContextRequest,
    SetWorkflowNodeCanCompleteRunRequest, SetWorkflowNodeCanEmitIntermediateOutputRequest,
    SetWorkflowNodeIntermediateOutputSchemaRequest, SetWorkflowNodeMaxTurnsRequest,
    SetWorkflowNodeWaitForAllInputsRequest, SetWorkflowRunOutputSchemaRequest,
    SetWorkflowScheduleEnabledRequest, SetWorkflowWatchdogEnabledRequest,
    SetWorkspaceLiveSyncModeRequest, ShowCloudSessionInviteRequest, ShowWorkspaceLinkRequest,
    SkillInstallSource, SliceCreateBase, SliceRefRequest, SliceStateResetRequest,
    SliceStateSaveMode, SliceStateSaveRequest, SliceStateSaveScope, SliceStateStatusRequest,
    SpawnAgentRequest, SpawnAgentsRequest, SpawnAgentsRequestItem, StartCloudRelayLoginRequest,
    StartEventGeneratorAuthorizationRequest, StartProviderLoginRequest,
    StartSliceProviderLoginRequest, SteerQueuedPromptRequest,
    StoreTransferredFileCapabilityRequest, SubmitPromptRequest, SubmitPromptsRequest,
    SubmitPromptsRequestItem, SyncRemoteExtensionManifestRequest, TeardownProviderProcessesRequest,
    TerminalCommandCatalog, TerminalCommandCatalogExecutionTarget, TerminalCommandCatalogNode,
    TerminalCommandCatalogNodeKind, TerminalCommandCatalogSurface, TerminalPairingLinkRecord,
    TerminalRecord, TerminalType, TestConnectorRequest, TestWorkflowEventBindingRequest,
    TransferWorkflowEventBindingRequest, TurnUndoResult, UndoTurnRequest,
    UninstallMcpServerRequest, UninstallSkillRequest, UnsetUserConfigValueRequest,
    UpdateAgentConfigRequest, UpdateAgentProfileRequest, UpdateAgentSubstitutesRequest,
    UpdateMcpServerRequest, UpdateMetaagentTaskRequest, UpdateProviderRunSelectionRequest,
    UpdateQueuedPromptRequest, UpdateQueuedWorkflowPromptRequest, UpdateSessionConfigRequest,
    UpdateSkillRequest, UpdateWorkflowCanvasLayoutRequest, UpdateWorkflowCodeArtifactRequest,
    UpdateWorkflowNodeInstructionsRequest, UpdateWorkflowPromptQueueRequest,
    UpsertConnectorRequest, UpsertCredentialRequest, UpsertSkillRequest, UserConfigMutationEffect,
    UserConfigProviderReloadSummary, ValidateScriptRequest, ValidateWorkflowCodeRequest,
    ValidateWorkflowHandoffRequest, WaitingRoomAgentRuntimePlacement, WaitingRoomInventorySnapshot,
    WaitingRoomLaunchTarget, WaitingRoomPublicAgentSummary, WaitingRoomPublicItemActivitySummary,
    WaitingRoomPublicProjectSummary, WaitingRoomPublicSessionSummary, WaitingRoomPublicSnapshot,
    WaitingRoomPublicWorkflowEdgeSummary, WaitingRoomPublicWorkflowEndpointSummary,
    WaitingRoomPublicWorkflowNodeSummary, WaitingRoomPublicWorkflowSummary,
    WaitingRoomSessionActivitySummary, WorkflowCodePackageExportTarget,
    WorkflowCodeSourceExportTarget, WorkflowDesignEdge, WorkflowDesignEdgePatch,
    WorkflowDesignEndpoint, WorkflowDesignEndpointPatch, WorkflowDesignNode,
    WorkflowDesignNodePatch, WorkflowDesignOp, WorkflowDesignOpForwarded, WorkflowDesignPoint,
    WorkflowDesignSchemaPatch, WorkflowDesignWorkflow, WorkflowDesignWorkflowPatch,
    WorkflowPublicationPackageFile, WorkflowPublicationRuntimeAction, WorkflowPublicationSnapshot,
    WorkflowPublicationSourceSessionSnapshot, WorkflowSchedulePreview,
    WorkspaceCommitMessageUtilityInput, WorkspaceFileContent, WorkspaceGitActionResult,
    WorkspaceGitChangeTotals, WorkspaceGitCompareRef, WorkspaceGitFileChange, WorkspaceGitOverview,
    WorkspaceLiveSyncConflictSummary, WorkspaceLiveSyncFooterState, WorkspaceLiveSyncGroupStatus,
    WorkspaceLiveSyncIgnoreStatus, WorkspaceLiveSyncStatus, WorkspaceLiveSyncTargetState,
    WorkspaceLiveSyncTargetStatus, WorkspacePullRequestRecord, WorkspaceRepoFileEntry,
    WorkspaceRepoFileListing, WorkspaceWorktreeRecord,
    DEPLOYMENT_CREDENTIAL_ENROLLMENT_SERVICE_SUBJECT_PREFIX, LOCAL_DAEMON_PROTOCOL_VERSION,
};
pub use client::LocalDaemonClient;
pub use harness::{run_local_harness, LocalHarnessReport};
pub use ipc::{run_local_ipc_server, send_local_ipc_request, LocalIpcClient};
