export function guessPathFenceLanguage(filePath: string | null | undefined): string {
  if (!filePath) {
    return "text"
  }
  const lower = filePath.toLowerCase()
  const name = lower.split(/[\\/]/).pop() ?? lower
  if (name === ".env") return "dotenv"
  if (name === "dockerfile") return "dockerfile"
  if (name === "makefile") return "makefile"
  if (lower.endsWith(".tsx") || lower.endsWith(".mtsx") || lower.endsWith(".ctsx")) return "typescriptreact"
  if (lower.endsWith(".ts") || lower.endsWith(".mts") || lower.endsWith(".cts")) return "typescript"
  if (lower.endsWith(".jsx")) return "javascriptreact"
  if (lower.endsWith(".js") || lower.endsWith(".mjs") || lower.endsWith(".cjs")) return "javascript"
  if (lower.endsWith(".html.erb") || lower.endsWith(".js.erb") || lower.endsWith(".json.erb")) return "erb"
  if (lower.endsWith(".json")) return "json"
  if (lower.endsWith(".md") || lower.endsWith(".markdown")) return "markdown"
  if (lower.endsWith(".rs")) return "rust"
  if (lower.endsWith(".py")) return "python"
  if (lower.endsWith(".go")) return "go"
  if (lower.endsWith(".java")) return "java"
  if (lower.endsWith(".kt") || lower.endsWith(".kts")) return "kotlin"
  if (lower.endsWith(".swift")) return "swift"
  if (lower.endsWith(".css")) return "css"
  if (lower.endsWith(".scss")) return "scss"
  if (lower.endsWith(".html") || lower.endsWith(".htm")) return "html"
  if (lower.endsWith(".xml")) return "xml"
  if (lower.endsWith(".yml") || lower.endsWith(".yaml")) return "yaml"
  if (lower.endsWith(".toml")) return "toml"
  if (lower.endsWith(".sh") || lower.endsWith(".bash") || lower.endsWith(".zsh")) return "shellscript"
  if (lower.endsWith(".sql")) return "sql"
  if (lower.endsWith(".tf")) return "terraform"
  if (lower.endsWith(".tfvars")) return "terraform-vars"
  if (lower.endsWith(".diff") || lower.endsWith(".patch")) return "diff"
  return "text"
}
