[Unit]
Requires=chariox-data-volume-admission.service
After=chariox-data-volume-admission.service
After=var-lib-chariox\x2ddocker-data.mount
BindsTo=var-lib-chariox\x2ddocker-data.mount
AssertPathIsMountPoint=/var/lib/chariox-docker/data
