[Unit]
Requires=chariox-data-volume-admission.service
After=chariox-data-volume-admission.service
After=var-lib-chariox\x2ddocker-data.mount
BindsTo=chariox-slice-disk-quota-allocator.service
AssertPathIsMountPoint=/var/lib/chariox-docker/data

[Service]
Environment=CHARIOX_PATH1_DATA_VOLUME_REQUIRED=1
