pub(crate) const AGENT_SPAWN_USAGE: &str = "agent spawn [alias] [model] [--provider <provider>] [--model <model>] [--effort <effort>|--variant <variant>] [--dir <directory>] [--worktree <directory> --branch <branch>] [--machine <machine-ref>|--kernel <kernel-ref>] [--slice off|new|new:headless|new:headed|<slice-ref>]";

use super::super::{MetaCommandDoc, MetaCommandPolicy};

pub(super) const COMMANDS: &[MetaCommandDoc] = &[
    MetaCommandDoc {
        name: "session overview",
        aliases: &["context", "agent list", "workflow list"],
        usage: "Use arroba.meta.session_overview for current session state.",
        examples: &["arroba.meta.session_overview({})"],
        tags: &["inspect", "session", "agents", "workflows"],
        intents: &[
            "inspect current session",
            "see existing agents",
            "check workflow state",
            "understand what is happening",
        ],
        scope: "session",
        mutates: false,
        policy: MetaCommandPolicy::Allow,
        authority: "current session",
        routed: true,
        description: "Inspect current session, owned agents, workflow runs, pending interactions, and event counts.",
    },
    MetaCommandDoc {
        name: "prompt",
        aliases: &["prompt <agent-ref> <text>"],
        usage: "prompt <owned-agent-ref> <prompt text>",
        examples: &["prompt agent-2 \"Investigate this failure\""],
        tags: &["prompt", "agent", "orchestration"],
        intents: &[
            "delegate work to an agent",
            "ask a worker to do a task",
            "send instructions to a regular agent",
            "have another agent implement something",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "owned regular agents",
        routed: true,
        description: "Submit a normal Arroba prompt to one of this user's regular agents through the existing prompt path. Do not use `prompt` to steer an agent that is currently running or queued for workflow work; inspect the workflow run and wait for its events instead. Metaagent prompt commands do not support blocking reply flags; use events, turn_overview, and turn_blob for supervision.",
    },
    MetaCommandDoc {
        name: "agent list",
        aliases: &["agent list", "agent ls"],
        usage: "agent list",
        examples: &["agent list"],
        tags: &["agent", "inspect", "orchestration"],
        intents: &[
            "list agents",
            "see available workers",
            "find existing agents",
            "inspect agent roster",
        ],
        scope: "session",
        mutates: false,
        policy: MetaCommandPolicy::Allow,
        authority: "owned and visible session agents",
        routed: true,
        description: "List agents in the current session so the metaagent can pick a regular worker to prompt or supervise.",
    },
    MetaCommandDoc {
        name: "agent spawn",
        aliases: &[
            "agent spawn",
            "agent create",
            "spawn agent",
            "create agent",
            "create worker",
            "make worker",
        ],
        usage: AGENT_SPAWN_USAGE,
        examples: &[
            "agent spawn reviewer gpt-5.2",
            "agent spawn verifier --provider opencode --model opencode/gpt-5.2 --effort high",
            "agent spawn verifier --dir ../qa",
            "agent spawn linux-checker --kernel linux-worker",
            "agent spawn isolated-builder --slice new:headless",
            "agent spawn slice-worker --slice linux-dev",
        ],
        tags: &["agent", "spawn", "worker", "orchestration"],
        intents: &[
            "create a new agent",
            "spawn a worker",
            "make a worker agent",
            "delegate implementation to a new agent",
            "start another agent for a task",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "owned agents only",
        routed: true,
        description: "Create a regular agent owned by the current user. Agents in Meta mode cannot spawn another agent in Meta mode. Spawn can choose provider, model, and effort/variant, and uses the same placement option contract as normal agent/session launch surfaces: directory placement, remote kernel placement, existing slice placement, and new slice creation.",
    },
    MetaCommandDoc {
        name: "agent focus",
        aliases: &["agent focus"],
        usage: "agent focus <agent-ref>",
        examples: &["agent focus reviewer"],
        tags: &["agent", "focus", "orchestration"],
        intents: &[
            "focus an agent",
            "switch selected agent",
            "make an agent current",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "owned agents only",
        routed: true,
        description: "Focus one of this user's agents in the current session.",
    },
    MetaCommandDoc {
        name: "agent alias",
        aliases: &["agent alias", "agent name"],
        usage: "agent alias <agent-ref> <alias>",
        examples: &["agent alias reviewer code-reviewer"],
        tags: &["agent", "alias", "rename", "orchestration"],
        intents: &[
            "rename an agent",
            "give an agent an alias",
            "label a worker",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "owned agents only",
        routed: true,
        description: "Assign or update a stable alias for one of this user's agents.",
    },
    MetaCommandDoc {
        name: "agent delete",
        aliases: &["agent delete", "agent destroy", "agent remove"],
        usage: "agent delete <agent-ref>",
        examples: &["agent delete code-reviewer"],
        tags: &["agent", "delete", "remove", "orchestration"],
        intents: &["delete an agent", "remove a worker", "clean up an agent"],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "owned agents only",
        routed: true,
        description: "Delete one of this user's regular agents from the current session.",
    },
];
