use super::super::{MetaCommandDoc, MetaCommandPolicy};

pub(super) const COMMANDS: &[MetaCommandDoc] = &[
    MetaCommandDoc {
        name: "mcp list",
        aliases: &["mcp", "mcp list", "mcp ls"],
        usage: "mcp list",
        examples: &["mcp list"],
        tags: &["extension", "mcp", "capability", "inspect"],
        intents: &[
            "list mcp tools",
            "see available mcp servers",
            "inspect worker tools",
        ],
        scope: "session",
        mutates: false,
        policy: MetaCommandPolicy::Allow,
        authority: "owned regular agents",
        routed: true,
        description: "List MCP definitions known to Arroba.",
    },
    MetaCommandDoc {
        name: "mcp show",
        aliases: &["mcp show", "mcp get"],
        usage: "mcp show <mcp-name>",
        examples: &["mcp show playwright"],
        tags: &["extension", "mcp", "capability", "inspect"],
        intents: &[
            "inspect mcp server",
            "show mcp config",
            "check mcp definition",
        ],
        scope: "session",
        mutates: false,
        policy: MetaCommandPolicy::Allow,
        authority: "owned regular agents",
        routed: true,
        description: "Inspect one MCP definition by name.",
    },
    MetaCommandDoc {
        name: "mcp install-json",
        aliases: &[
            "mcp install-json",
            "mcp update-json",
            "install mcp",
            "add mcp",
        ],
        usage: "mcp install-json '<mcp-json>'",
        examples: &[
            "mcp install-json '{\"name\":\"playwright\",\"transport\":{\"type\":\"stdio\",\"command\":\"npx\",\"args\":[\"@playwright/mcp\"],\"env\":{},\"env_vars\":[]},\"enabled\":true,\"required\":false}'",
        ],
        tags: &["extension", "mcp", "capability", "install", "tool"],
        intents: &[
            "install an mcp server",
            "add a tool provider",
            "make a new mcp capability available",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "owned regular agents",
        routed: true,
        description: "Install or update an MCP definition through existing kernel extension policy.",
    },
    MetaCommandDoc {
        name: "mcp update-json",
        aliases: &["mcp update-json", "update mcp"],
        usage: "mcp update-json '<mcp-json>'",
        examples: &[
            "mcp update-json '{\"name\":\"playwright\",\"transport\":{\"type\":\"stdio\",\"command\":\"npx\",\"args\":[\"@playwright/mcp\"],\"env\":{},\"env_vars\":[]},\"enabled\":true,\"required\":false}'",
        ],
        tags: &["extension", "mcp", "capability", "update", "tool"],
        intents: &[
            "update mcp server",
            "change mcp config",
            "replace mcp definition",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "owned regular agents",
        routed: true,
        description: "Update an existing MCP definition through existing kernel extension policy.",
    },
    MetaCommandDoc {
        name: "mcp grant",
        aliases: &[
            "mcp grant",
            "mcp revoke",
            "grant mcp",
            "give worker tool",
            "give agent mcp",
        ],
        usage: "mcp grant <agent-ref> <mcp-name>",
        examples: &["mcp grant agent-2 playwright"],
        tags: &["extension", "mcp", "capability", "grant", "tool"],
        intents: &[
            "give a worker an mcp tool",
            "grant a tool to an agent",
            "enable mcp for a regular agent",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "owned regular agents",
        routed: true,
        description: "Grant or revoke an MCP extension for one of this user's regular agents. Agents in Meta mode cannot grant MCP tools to themselves.",
    },
    MetaCommandDoc {
        name: "mcp uninstall",
        aliases: &["mcp uninstall", "mcp remove"],
        usage: "mcp uninstall <mcp-name>",
        examples: &["mcp uninstall playwright"],
        tags: &["extension", "mcp", "capability", "remove", "tool"],
        intents: &[
            "remove mcp server",
            "uninstall tool provider",
            "delete mcp capability",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "owned regular agents",
        routed: true,
        description: "Remove an MCP definition through existing kernel extension policy.",
    },
    MetaCommandDoc {
        name: "mcp revoke",
        aliases: &["mcp revoke", "revoke mcp", "remove worker mcp"],
        usage: "mcp revoke <agent-ref> <mcp-name>",
        examples: &["mcp revoke agent-2 playwright"],
        tags: &["extension", "mcp", "capability", "revoke", "tool"],
        intents: &[
            "remove tool from worker",
            "revoke mcp from agent",
            "disable agent mcp",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "owned regular agents",
        routed: true,
        description: "Revoke an MCP extension from one of this user's regular agents.",
    },
    MetaCommandDoc {
        name: "mcp import",
        aliases: &[
            "mcp import",
            "import mcp",
            "import provider mcp",
            "sync mcp from provider",
        ],
        usage: "mcp import <codex|opencode|claude> [mcp-name]",
        examples: &[
            "mcp import codex playwright",
            "mcp import opencode",
            "mcp import claude docs",
        ],
        tags: &[
            "extension",
            "mcp",
            "capability",
            "import",
            "provider",
            "tool",
            "discover",
        ],
        intents: &[
            "import mcp from provider config",
            "bring existing mcp into arroba",
            "make a provider mcp grantable",
            "sync local provider mcp tools",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "owned regular agents",
        routed: true,
        description: "Import MCP definitions from a local provider configuration into the Arroba registry. Only Arroba-registered MCPs can be granted to workers, so list or show MCPs after importing before using `mcp grant`.",
    },
    MetaCommandDoc {
        name: "skill list",
        aliases: &["skill", "skill list", "skills list", "skill ls", "skills"],
        usage: "skill list",
        examples: &["skill list"],
        tags: &["extension", "skill", "capability", "inspect"],
        intents: &[
            "list skills",
            "see available skills",
            "inspect worker skills",
        ],
        scope: "session",
        mutates: false,
        policy: MetaCommandPolicy::Allow,
        authority: "owned regular agents",
        routed: true,
        description: "List skills known to Arroba.",
    },
    MetaCommandDoc {
        name: "skill show",
        aliases: &["skill show", "skill get", "skills show", "skills get"],
        usage: "skill show <skill-name>",
        examples: &["skill show browser-qa"],
        tags: &["extension", "skill", "capability", "inspect"],
        intents: &[
            "inspect skill",
            "show skill config",
            "check skill definition",
        ],
        scope: "session",
        mutates: false,
        policy: MetaCommandPolicy::Allow,
        authority: "owned regular agents",
        routed: true,
        description: "Inspect one skill definition by name.",
    },
    MetaCommandDoc {
        name: "skill install",
        aliases: &[
            "skill install",
            "skill update",
            "install skill",
            "add skill",
        ],
        usage: "skill install <path-or-name>",
        examples: &["skill install ./skills/browser-qa"],
        tags: &["extension", "skill", "capability", "install", "tool"],
        intents: &["install a skill", "add a skill", "make a skill available"],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "owned regular agents",
        routed: true,
        description: "Install or update a skill through existing kernel extension policy.",
    },
    MetaCommandDoc {
        name: "skill update",
        aliases: &["skill update", "skills update", "update skill"],
        usage: "skill update <path-or-name>",
        examples: &["skill update ./skills/browser-qa"],
        tags: &["extension", "skill", "capability", "update", "tool"],
        intents: &["update skill", "change skill", "replace skill definition"],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "owned regular agents",
        routed: true,
        description: "Update an installed skill through existing kernel extension policy.",
    },
    MetaCommandDoc {
        name: "skill grant",
        aliases: &[
            "skill grant",
            "skill revoke",
            "grant skill",
            "give worker skill",
            "give agent skill",
        ],
        usage: "skill grant <agent-ref> <skill-name>",
        examples: &["skill grant agent-2 browser-qa"],
        tags: &["extension", "skill", "capability", "grant", "tool"],
        intents: &[
            "give a worker a skill",
            "grant a skill to an agent",
            "enable skill for a regular agent",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "owned regular agents",
        routed: true,
        description: "Grant or revoke a skill for one of this user's regular agents. Agents in Meta mode cannot grant skills to themselves.",
    },
    MetaCommandDoc {
        name: "skill uninstall",
        aliases: &["skill uninstall", "skill remove"],
        usage: "skill uninstall <skill-name>",
        examples: &["skill uninstall browser-qa"],
        tags: &["extension", "skill", "capability", "remove", "tool"],
        intents: &["remove skill", "uninstall skill", "delete worker skill"],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "owned regular agents",
        routed: true,
        description: "Remove a skill through existing kernel extension policy.",
    },
    MetaCommandDoc {
        name: "skill revoke",
        aliases: &["skill revoke", "revoke skill", "remove worker skill"],
        usage: "skill revoke <agent-ref> <skill-name>",
        examples: &["skill revoke agent-2 browser-qa"],
        tags: &["extension", "skill", "capability", "revoke", "tool"],
        intents: &[
            "remove skill from worker",
            "revoke skill from agent",
            "disable agent skill",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "owned regular agents",
        routed: true,
        description: "Revoke a skill from one of this user's regular agents.",
    },
    MetaCommandDoc {
        name: "skill import",
        aliases: &[
            "skill import",
            "skills import",
            "import skill",
            "import provider skill",
            "sync skill from provider",
        ],
        usage: "skill import <codex|opencode|claude> [skill-name]",
        examples: &[
            "skill import codex browser-qa",
            "skill import opencode",
            "skill import claude docs-helper",
        ],
        tags: &[
            "extension",
            "skill",
            "capability",
            "import",
            "provider",
            "tool",
            "discover",
        ],
        intents: &[
            "import skill from provider config",
            "bring existing skill into arroba",
            "make a provider skill grantable",
            "sync local provider skills",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "owned regular agents",
        routed: true,
        description: "Import skills from local provider skill directories into the Arroba registry. Only Arroba-registered skills can be granted to workers, so list or show skills after importing before using `skill grant`.",
    },
    MetaCommandDoc {
        name: "extension import providers",
        aliases: &[
            "extension import providers",
            "extensions import providers",
            "sync provider capabilities",
            "import all provider capabilities",
            "import provider mcps and skills",
        ],
        usage: "extension import providers [--provider codex|opencode|claude] [--kind all|mcp|skill] [--name <capability>] [--dry-run]",
        examples: &[
            "extension import providers --dry-run",
            "extension import providers --provider codex --provider claude --kind all",
            "extension import providers --provider claude --kind skill --name docs-helper",
        ],
        tags: &[
            "extension",
            "mcp",
            "skill",
            "capability",
            "import",
            "provider",
            "sync",
            "dedupe",
            "discover",
        ],
        intents: &[
            "import all provider mcps and skills",
            "sync local provider capabilities into arroba",
            "deduplicate provider tools before granting",
            "make provider capabilities available to grant",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "owned regular agents",
        routed: true,
        description: "Discover Codex, OpenCode, and Claude MCPs and skills, deduplicate by capability kind/name/hash, import or update the selected newest definitions in the Arroba registries, and return a compact report. Use this when you are not sure whether a needed MCP or skill is already installed in Arroba; run with `--dry-run` first if you only need discovery.",
    },
];
