use super::super::{MetaCommandDoc, MetaCommandPolicy};

pub(super) const COMMANDS: &[MetaCommandDoc] = &[
    MetaCommandDoc {
        name: "slice",
        aliases: &["slice list", "slice show", "slice save", "slice save-state", "slice stop"],
        usage: "slice <list|show|start|stop|save-state|status|backup> ...",
        examples: &[
            "slice list",
            "slice show dev",
            "slice save-state dev --restart-agents --this-slice",
            "slice stop dev",
        ],
        tags: &["slice", "environment"],
        intents: &["manage slice", "save slice state", "stop environment"],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "kernel-managed slice lifecycle without credential mutation",
        routed: true,
        description: "Inspect and manage slice lifecycle through the kernel. Creating a slice remains composed with `agent spawn <alias> --slice <slice-ref|new|new:headless|new:headed>` so its worker ownership is explicit.",
    },
    MetaCommandDoc {
        name: "credential list",
        aliases: &[
            "credential",
            "credential list",
            "credential ls",
            "credentials list",
        ],
        usage: "credential list",
        examples: &["credential list"],
        tags: &["credential", "vault", "sensitive", "inspect"],
        intents: &[
            "list credentials",
            "see credential handles",
            "inspect available secrets",
        ],
        scope: "global",
        mutates: false,
        policy: MetaCommandPolicy::Allow,
        authority: "credential handle metadata only",
        routed: true,
        description: "List credential handles without exposing raw secret values.",
    },
    MetaCommandDoc {
        name: "credential get",
        aliases: &["credential get", "credential show", "credentials get"],
        usage: "credential get <credential-id>",
        examples: &["credential get credential-1"],
        tags: &["credential", "vault", "sensitive", "inspect"],
        intents: &[
            "inspect credential",
            "view credential metadata",
            "check credential handle",
        ],
        scope: "global",
        mutates: false,
        policy: MetaCommandPolicy::Allow,
        authority: "credential handle metadata only",
        routed: true,
        description: "Inspect credential handle metadata without exposing raw secret values.",
    },
    MetaCommandDoc {
        name: "credential upsert-json",
        aliases: &[
            "credential upsert-json",
            "create credential",
            "store credential",
            "add credential handle",
        ],
        usage: "credential upsert-json '<credential-json>'",
        examples: &[
            "credential upsert-json '{\"id\":\"github-token\",\"source\":{\"type\":\"vault\",\"key\":\"github-token\"},\"allowed_uses\":[\"http\"],\"injection\":{\"kind\":\"header\",\"name\":\"authorization\",\"value\":\"Bearer ${secret}\"}}'",
        ],
        tags: &["credential", "vault", "sensitive", "create"],
        intents: &[
            "create credential handle",
            "store credential metadata",
            "add a credential",
            "prepare a secret for worker use",
        ],
        scope: "global",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "credential handle metadata and vault unlock only",
        routed: true,
        description: "Create or update a credential handle. Secret values are never accepted as metaagent command arguments.",
    },
    MetaCommandDoc {
        name: "credential remove",
        aliases: &["credential remove"],
        usage: "credential remove <credential-id>",
        examples: &["credential remove credential-1"],
        tags: &["credential", "vault", "sensitive", "remove"],
        intents: &["remove credential handle", "delete credential metadata"],
        scope: "global",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "credential handle metadata only",
        routed: true,
        description: "Remove a credential handle without reading raw secret values.",
    },
    MetaCommandDoc {
        name: "credential vault",
        aliases: &["credential vault status", "credential vault manage"],
        usage: "credential vault <status|manage>",
        examples: &["credential vault status", "credential vault manage"],
        tags: &["credential", "vault", "sensitive"],
        intents: &[
            "open vault management",
            "check vault status",
            "enter new secret in vault",
        ],
        scope: "global",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "vault unlock and management request only",
        routed: true,
        description: "Request vault status or user-facing vault management. Raw secret values are not returned to the metaagent.",
    },
    MetaCommandDoc {
        name: "credential secret mutation",
        aliases: &[
            "credential set",
            "credential set-secret",
            "credential delete-secret",
        ],
        usage: "credential set|set-secret|delete-secret ...",
        examples: &[],
        tags: &["credential", "vault", "sensitive"],
        intents: &[
            "set secret value",
            "delete secret value",
            "write raw secret",
        ],
        scope: "global",
        mutates: true,
        policy: MetaCommandPolicy::Deny,
        authority: "denied",
        routed: false,
        description: "Denied for agents in Meta mode. Secret values must be entered through user or worker credential interactions, not Meta mode command text.",
    },
    MetaCommandDoc {
        name: "session new",
        aliases: &[
            "session create",
            "session attach",
            "session use",
            "session delete",
        ],
        usage: "session new|create|attach|use|delete ...",
        examples: &[],
        tags: &["session", "denied"],
        intents: &[
            "create session",
            "attach session",
            "switch session",
            "delete session",
        ],
        scope: "global",
        mutates: true,
        policy: MetaCommandPolicy::Deny,
        authority: "denied",
        routed: false,
        description: "Denied for agents in Meta mode. Agents in Meta mode must operate inside their containing session.",
    },
];
