use super::super::{MetaCommandDoc, MetaCommandPolicy};

pub(super) const COMMANDS: &[MetaCommandDoc] = &[
    MetaCommandDoc {
        name: "workflow list",
        aliases: &["workflow", "workflow list", "workflow ls"],
        usage: "workflow list",
        examples: &["workflow list"],
        tags: &["workflow", "inspect", "orchestration"],
        intents: &[
            "list workflows",
            "see workflow definitions",
            "inspect workflow runs",
        ],
        scope: "session",
        mutates: false,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: true,
        description: "List workflow definitions and runs visible in the current session.",
    },
    MetaCommandDoc {
        name: "workflow new",
        aliases: &["workflow new", "workflow create", "create workflow"],
        usage: "workflow new <workflow-name>",
        examples: &["workflow new qa-flow"],
        tags: &["workflow", "create", "orchestration"],
        intents: &[
            "create a workflow",
            "make an automation graph",
            "start a workflow plan",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: true,
        description: "Create a workflow definition that can coordinate regular agents.",
    },
    MetaCommandDoc {
        name: "workflow resolve",
        aliases: &["workflow resolve", "workflow show", "workflow get"],
        usage: "workflow resolve <workflow-ref>",
        examples: &["workflow resolve qa-flow"],
        tags: &["workflow", "inspect", "orchestration"],
        intents: &[
            "inspect workflow definition",
            "get workflow node ids",
            "find workflow endpoint ids",
            "review workflow graph",
        ],
        scope: "session",
        mutates: false,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: true,
        description: "Resolve a workflow reference to the full workflow definition, including node, edge, and endpoint ids needed by other workflow commands.",
    },
    MetaCommandDoc {
        name: "workflow alias",
        aliases: &["workflow alias", "workflow name", "rename workflow"],
        usage: "workflow alias <workflow-ref> <alias>",
        examples: &["workflow alias wf_123 qa-flow"],
        tags: &["workflow", "rename", "orchestration"],
        intents: &[
            "rename workflow",
            "give workflow a stable alias",
            "label workflow",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: true,
        description: "Assign or update a human-readable workflow alias.",
    },
    MetaCommandDoc {
        name: "workflow node add",
        aliases: &["workflow node add", "add workflow node"],
        usage: "workflow node add <workflow-ref> <agent-ref>",
        examples: &["workflow node add qa-flow reviewer"],
        tags: &["workflow", "node", "agent", "orchestration"],
        intents: &[
            "add a worker to a workflow",
            "put an agent in a workflow",
            "create a workflow node",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy; regular agents only",
        routed: true,
        description: "Add a regular agent as a node in a workflow. Use the agent alias as the human label; workflow nodes do not take a separate alias. Agents in Meta mode cannot be workflow nodes.",
    },
    MetaCommandDoc {
        name: "workflow node remove",
        aliases: &[
            "workflow node remove",
            "workflow node delete",
            "remove workflow node",
        ],
        usage: "workflow node remove <workflow-ref> <node-id>",
        examples: &["workflow node remove qa-flow node_123"],
        tags: &["workflow", "node", "remove", "orchestration"],
        intents: &[
            "remove workflow node",
            "delete workflow node",
            "take agent out of workflow",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: true,
        description: "Remove a workflow node by node id. Resolve or list the workflow first if you need node ids.",
    },
    MetaCommandDoc {
        name: "workflow node instructions",
        aliases: &["workflow node instructions", "workflow node instruct"],
        usage: "workflow node instructions <workflow-ref> <node-id> [instructions]",
        examples: &[
            "workflow node instructions qa-flow node_123 \"Review implementation and report risks\"",
        ],
        tags: &["workflow", "node", "instructions", "orchestration"],
        intents: &[
            "set node instructions",
            "describe node task",
            "change worker instructions",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: true,
        description: "Set or clear per-node workflow instructions. Use `clear`, `none`, or `-` as the instructions value to clear them.",
    },
    MetaCommandDoc {
        name: "workflow node can-complete",
        aliases: &["workflow node can-complete", "workflow node complete"],
        usage: "workflow node can-complete <workflow-ref> <node-id> <true|false>",
        examples: &["workflow node can-complete qa-flow node_123 true"],
        tags: &["workflow", "node", "completion", "orchestration"],
        intents: &[
            "allow node to complete workflow",
            "set final node",
            "prevent node completion",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: true,
        description: "Control whether a node may emit final workflow output and complete the run.",
    },
    MetaCommandDoc {
        name: "workflow node intermediate-output",
        aliases: &[
            "workflow node intermediate-output",
            "workflow node intermediate",
        ],
        usage: "workflow node intermediate-output <workflow-ref> <node-id> <true|false>",
        examples: &["workflow node intermediate-output qa-flow node_123 true"],
        tags: &["workflow", "node", "output", "orchestration"],
        intents: &[
            "allow intermediate output",
            "publish user-visible progress output",
            "disable intermediate output",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: true,
        description: "Control whether a node may emit user-visible intermediate workflow output events while the run continues.",
    },
    MetaCommandDoc {
        name: "workflow node wait-for-all-inputs",
        aliases: &[
            "workflow node wait-for-all-inputs",
            "workflow node wait-all",
            "workflow node join",
        ],
        usage: "workflow node wait-for-all-inputs <workflow-ref> <node-id> <true|false>",
        examples: &["workflow node wait-for-all-inputs qa-flow node_123 true"],
        tags: &["workflow", "node", "join", "inputs", "orchestration"],
        intents: &[
            "wait for all workflow inputs",
            "join parallel workflow branches",
            "synchronize workflow inputs",
            "combine branch outputs by iteration",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: true,
        description: "Control whether a node waits until every incoming edge has an unconsumed handoff from the same source-node iteration before it runs. Use this for join nodes that combine parallel branches.",
    },
    MetaCommandDoc {
        name: "workflow node intermediate-output-schema",
        aliases: &[
            "workflow node intermediate-output-schema",
            "workflow node intermediate schema",
        ],
        usage: "workflow node intermediate-output-schema <workflow-ref> <node-id> <schema-ref|none>",
        examples: &[],
        tags: &["workflow", "node", "schema", "output", "orchestration"],
        intents: &[
            "set intermediate output schema",
            "validate user-visible intermediate output",
            "clear intermediate output schema",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: false,
        description: "Documented workflow capability, not routed through metaagent run_command yet. Use worker instructions and available workflow output tools unless schema routing is explicitly added.",
    },
    MetaCommandDoc {
        name: "workflow node max-turns",
        aliases: &["workflow node max-turns", "workflow node turn limit"],
        usage: "workflow node max-turns <workflow-ref> <node-id> <number|none>",
        examples: &["workflow node max-turns qa-flow node_123 3"],
        tags: &["workflow", "node", "limit", "orchestration"],
        intents: &["limit node turns", "set max turns", "clear node turn limit"],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: true,
        description: "Set or clear the maximum number of turns a workflow node may take in one run.",
    },
    MetaCommandDoc {
        name: "workflow endpoint new",
        aliases: &["workflow endpoint new", "workflow endpoint create"],
        usage: "workflow endpoint new <workflow-ref> <node-ref> <endpoint-name>",
        examples: &["workflow endpoint new qa-flow node-1 default"],
        tags: &["workflow", "endpoint", "orchestration"],
        intents: &[
            "create workflow endpoint",
            "make workflow entrypoint",
            "wire workflow input",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: true,
        description: "Create an endpoint that can start a workflow run.",
    },
    MetaCommandDoc {
        name: "workflow endpoint alias",
        aliases: &[
            "workflow endpoint alias",
            "workflow endpoint name",
            "rename workflow endpoint",
        ],
        usage: "workflow endpoint alias <workflow-ref> <endpoint-ref> <alias>",
        examples: &["workflow endpoint alias qa-flow endpoint_123 start"],
        tags: &["workflow", "endpoint", "rename", "orchestration"],
        intents: &[
            "rename endpoint",
            "label workflow entrypoint",
            "give endpoint alias",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: true,
        description: "Assign or update a human-readable alias for a workflow endpoint.",
    },
    MetaCommandDoc {
        name: "workflow endpoint bind",
        aliases: &["workflow endpoint bind"],
        usage: "workflow endpoint bind <workflow-ref> <endpoint-ref> <queue-ref>",
        examples: &[],
        tags: &["workflow", "endpoint", "queue", "orchestration"],
        intents: &[
            "bind workflow endpoint",
            "connect endpoint to queue",
            "attach workflow endpoint",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: false,
        description: "Documented daemon capability, not routed through metaagent run_command yet. For ordinary metaagent workflow runs, create an endpoint and invoke it directly with `workflow run`.",
    },
    MetaCommandDoc {
        name: "workflow endpoint remove",
        aliases: &["workflow endpoint remove", "workflow endpoint delete"],
        usage: "workflow endpoint remove <workflow-ref> <endpoint-ref>",
        examples: &[],
        tags: &["workflow", "endpoint", "remove", "orchestration"],
        intents: &["remove workflow endpoint", "delete workflow endpoint"],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "not implemented",
        routed: false,
        description: "Documented as unavailable for metaagents: endpoint removal is not currently exposed through the kernel command router. Prefer aliasing or creating a new endpoint.",
    },
    MetaCommandDoc {
        name: "workflow edge add",
        aliases: &[
            "workflow edge add",
            "add workflow edge",
            "connect workflow nodes",
            "connect nodes",
        ],
        usage: "workflow edge add <workflow-ref> <from-node-id> <to-node-id>",
        examples: &["workflow edge add qa-flow node_a node_b"],
        tags: &["workflow", "edge", "connect", "orchestration"],
        intents: &[
            "connect workflow nodes",
            "add edge between nodes",
            "make workflow sequential",
            "send output from one node to another",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: true,
        description: "Connect two workflow nodes so output can flow from the source node to the target node.",
    },
    MetaCommandDoc {
        name: "workflow edge remove",
        aliases: &[
            "workflow edge remove",
            "workflow edge delete",
            "remove workflow edge",
        ],
        usage: "workflow edge remove <workflow-ref> <edge-id>",
        examples: &["workflow edge remove qa-flow edge_123"],
        tags: &["workflow", "edge", "remove", "orchestration"],
        intents: &[
            "remove workflow edge",
            "disconnect workflow nodes",
            "delete edge",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: true,
        description: "Remove an edge from a workflow by edge id. Resolve the workflow first if you need edge ids.",
    },
    MetaCommandDoc {
        name: "workflow run",
        aliases: &[
            "workflow run",
            "workflow start",
            "run workflow",
            "start workflow",
        ],
        usage: "workflow run <workflow-ref> <endpoint-ref> <prompt>",
        examples: &["workflow run qa-flow default \"Run QA\""],
        tags: &["workflow", "run", "orchestration"],
        intents: &[
            "run a workflow",
            "start a workflow",
            "execute an automation graph",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: true,
        description: "Start a workflow run from an endpoint with a prompt.",
    },
    MetaCommandDoc {
        name: "workflow runs",
        aliases: &["workflow runs"],
        usage: "workflow runs [workflow-ref]",
        examples: &["workflow runs qa-flow"],
        tags: &["workflow", "inspect", "runs", "orchestration"],
        intents: &[
            "list workflow runs",
            "inspect workflow run status",
            "check workflow progress",
        ],
        scope: "session",
        mutates: false,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: true,
        description: "List workflow runs and their current status.",
    },
    MetaCommandDoc {
        name: "workflow get-run",
        aliases: &[
            "workflow get-run",
            "workflow run-status",
            "workflow run get",
        ],
        usage: "workflow get-run <run-ref>",
        examples: &["workflow get-run run_123"],
        tags: &["workflow", "inspect", "runs", "orchestration"],
        intents: &[
            "inspect workflow run",
            "check workflow run details",
            "read workflow output",
        ],
        scope: "session",
        mutates: false,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: true,
        description: "Fetch a single workflow run and its detailed status/output by run reference.",
    },
    MetaCommandDoc {
        name: "workflow tutorial basic",
        aliases: &[
            "workflow guide",
            "workflow tutorial",
            "how to build workflow",
            "workflow example",
        ],
        usage: "Read-only guide entry. Use command_docs(\"workflow tutorial basic\") or search_commands(\"build workflow tutorial\").",
        examples: &[
            "workflow new qa-flow",
            "agent spawn implementer",
            "agent spawn reviewer",
            "workflow node add qa-flow implementer",
            "workflow node add qa-flow reviewer",
            "workflow resolve qa-flow",
            "workflow node instructions qa-flow <implementer-node-id> \"Implement the change, run checks, and hand off files plus command results\"",
            "workflow node instructions qa-flow <reviewer-node-id> \"Review independently, run checks, and complete only on pass\"",
            "workflow node can-complete qa-flow <reviewer-node-id> true",
            "workflow edge add qa-flow <implementer-node-id> <reviewer-node-id>",
            "workflow endpoint new qa-flow <entry-node-id> start",
            "workflow run qa-flow start \"Build and verify the app\"",
            "workflow runs qa-flow",
            "workflow get-run <run-ref>",
        ],
        tags: &["workflow", "guide", "tutorial", "orchestration"],
        intents: &[
            "learn workflow basics",
            "build workflow from scratch",
            "connect nodes and run workflow",
            "create endpoint and trigger workflow",
        ],
        scope: "session",
        mutates: false,
        policy: MetaCommandPolicy::Allow,
        authority: "documentation only",
        routed: false,
        description: "Basic workflow sequence: create the workflow, spawn regular agents, add each agent as a node, resolve the workflow to get node ids, configure node instructions and completion permissions, connect nodes with edges when work should flow between them, create an endpoint on the entry node, run the endpoint with the task prompt, then inspect runs or a specific run. Configure nodes before running; instruction changes after a run starts do not rewrite the already-dispatched turn. While a run is Running, use `workflow get-run`, events, and turn_overview for visibility. Do not direct-prompt workflow workers, create replacement workflows, or cancel/restart the run unless the run is truly blocked or the user asked to abort. Workflow nodes use agent aliases; node ids come from workflow resolve/list output.",
    },
    MetaCommandDoc {
        name: "workflow run-output-schema",
        aliases: &["workflow run-output-schema", "workflow output schema"],
        usage: "workflow run-output-schema <workflow-ref> <schema-ref|none>",
        examples: &[],
        tags: &["workflow", "schema", "output", "orchestration"],
        intents: &[
            "set workflow final output schema",
            "validate workflow output",
            "clear workflow output schema",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: false,
        description: "Documented workflow capability, not routed through metaagent run_command yet. Use workflow guides and worker output validation until schema routing is added.",
    },
    MetaCommandDoc {
        name: "workflow max-turns",
        aliases: &["workflow max-turns", "workflow turn limit"],
        usage: "workflow max-turns <workflow-ref> <number|none>",
        examples: &[],
        tags: &["workflow", "limit", "orchestration"],
        intents: &[
            "set workflow turn limit",
            "limit workflow turns",
            "clear workflow turn limit",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "not implemented",
        routed: false,
        description: "Workflow-level max-turns is not currently exposed as a metaagent command. Use `workflow node max-turns` for per-node limits.",
    },
    MetaCommandDoc {
        name: "workflow node extensions",
        aliases: &[
            "workflow node extensions",
            "workflow node grant",
            "workflow node revoke",
        ],
        usage: "workflow node extensions ...",
        examples: &[],
        tags: &["workflow", "node", "extension", "capability"],
        intents: &[
            "grant tool to workflow node",
            "revoke tool from workflow node",
            "configure node extensions",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "owned regular agents",
        routed: false,
        description: "Workflow-node extension commands are not routed directly. Grant MCPs or skills to the owned regular agent with `mcp grant` or `skill grant`; the workflow node inherits the agent capability.",
    },
    MetaCommandDoc {
        name: "workflow pane",
        aliases: &[
            "workflow pane",
            "workflow log",
            "workflow trace",
            "workflow edit",
        ],
        usage: "workflow <pane|log|trace|edit> ...",
        examples: &[],
        tags: &["workflow", "ui", "inspect", "cli-only"],
        intents: &[
            "open workflow pane",
            "view workflow log",
            "inspect workflow trace",
            "edit workflow visually",
        ],
        scope: "session",
        mutates: false,
        policy: MetaCommandPolicy::Deny,
        authority: "denied",
        routed: false,
        description: "CLI/TUI workflow UI commands are not available to metaagents. Use `workflow resolve`, `workflow runs`, `workflow get-run`, events, and turn_overview instead.",
    },
    MetaCommandDoc {
        name: "workflow cancel",
        aliases: &["workflow cancel"],
        usage: "workflow cancel <run-ref>",
        examples: &["workflow cancel run-1"],
        tags: &["workflow", "cancel", "orchestration"],
        intents: &[
            "cancel a workflow",
            "stop a workflow run",
            "abort workflow run",
        ],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: true,
        description: "Cancel an active workflow run.",
    },
    MetaCommandDoc {
        name: "workflow resume",
        aliases: &["workflow resume"],
        usage: "workflow resume <run-ref>",
        examples: &["workflow resume run-1"],
        tags: &["workflow", "resume", "orchestration"],
        intents: &["resume a workflow", "continue a paused workflow run"],
        scope: "session",
        mutates: true,
        policy: MetaCommandPolicy::Allow,
        authority: "session workflow policy",
        routed: true,
        description: "Resume a paused or resumable workflow run. Do not call this on a Running workflow; poll `workflow get-run`, wait for workflow events, or inspect worker turns instead.",
    },
    MetaCommandDoc {
        name: "agent app guide",
        aliases: &[
            "generate agent app",
            "agent app tutorial",
            "workflow app guide",
            "build web app with agents",
        ],
        usage: "Read-only guide entry. Use command_docs(\"agent app guide\") or search_commands(\"generate agent app\").",
        examples: &[
            "workflow new app-build",
            "agent spawn builder",
            "agent spawn verifier",
            "workflow node add app-build builder",
            "workflow node add app-build verifier",
            "workflow resolve app-build",
            "workflow node instructions app-build <builder-node-id> \"Build the app, run checks, and hand off files plus command results\"",
            "workflow node instructions app-build <verifier-node-id> \"Review independently, run checks, and complete only on pass\"",
            "workflow node can-complete app-build <verifier-node-id> true",
            "workflow edge add app-build <builder-node-id> <verifier-node-id>",
            "workflow endpoint new app-build <builder-node-id> start",
            "workflow run app-build start \"Build the requested app, then verify it\"",
            "workflow get-run <run-ref>",
        ],
        tags: &["guide", "workflow", "agent-app", "webapp", "orchestration"],
        intents: &[
            "generate agent app",
            "build web app with workflow",
            "create app using agents",
            "verify generated application",
        ],
        scope: "session",
        mutates: false,
        policy: MetaCommandPolicy::Allow,
        authority: "documentation only",
        routed: false,
        description: "For app-building tasks, use a workflow when requested: create builder and verifier regular agents, add them as workflow nodes, resolve node ids, configure builder/reviewer node instructions, set only the verifier node as able to complete the run, connect builder to verifier, create an endpoint on the builder node, run the workflow with the user's high-level app prompt, then inspect the run and worker turns. The app should be built by the workflow run, not by direct prompts outside the run. While the run is active, wait for final workflow JSON, workflow events, or clear failure before retrying. The metaagent should supervise and complete the task only after the workflow output and worker evidence show the app was built and verified.",
    },
];
