import { createHash } from "node:crypto"
import { constants } from "node:fs"
import { open } from "node:fs/promises"
import { resolve } from "node:path"

export type PublisherMaterial = { publisherId: string; keyId: string; publicKeyBase64: string }
const invalid = () => new Error("Choose the public publisher.json generated by chariox app keygen")
function object(value: unknown, keys: string[]): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)
    || Object.keys(value).sort().join("|") !== [...keys].sort().join("|")) throw invalid()
  return value as Record<string, unknown>
}

/** Public review material only. The kernel independently validates and enrolls it. */
export async function readPublisherFile(selected: string, cwd: string): Promise<PublisherMaterial> {
  if (!selected || selected.includes("\0") || Buffer.byteLength(selected) > 4096) throw invalid()
  const file = await open(resolve(cwd, selected), constants.O_RDONLY | constants.O_NOFOLLOW | constants.O_NONBLOCK)
  try {
    const before = await file.stat({ bigint: true })
    if (!before.isFile() || before.size < 1n || before.size > 16384n) throw invalid()
    const bytes = Buffer.alloc(Number(before.size) + 1)
    let size = 0
    while (size < bytes.length) {
      const part = await file.read(bytes, size, bytes.length - size, size)
      if (!part.bytesRead) break
      size += part.bytesRead
    }
    const after = await file.stat({ bigint: true })
    if (BigInt(size) !== before.size || before.size !== after.size
      || before.mtimeNs !== after.mtimeNs || before.ctimeNs !== after.ctimeNs) {
      throw new Error("The public publisher file changed while it was being read")
    }
    let value: unknown
    try { value = JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(bytes.subarray(0, size))) }
    catch { throw invalid() }
    const data = object(value, ["schema", "algorithm", "publisher", "publicKey"])
    const publisher = object(data.publisher, ["id", "keyId", "name"])
    if (data.schema !== "chariox.developer-publisher.v1" || data.algorithm !== "ed25519"
      || typeof data.publicKey !== "string" || data.publicKey.length !== 44
      || typeof publisher.id !== "string" || !/^[a-zA-Z0-9][a-zA-Z0-9._-]{0,127}$/.test(publisher.id)
      || typeof publisher.name !== "string" || !publisher.name.trim() || Buffer.byteLength(publisher.name) > 256) throw invalid()
    const key = Buffer.from(data.publicKey, "base64")
    if (key.length !== 32 || key.toString("base64") !== data.publicKey
      || publisher.keyId !== `dev-${createHash("sha256").update(key).digest("hex")}`) throw invalid()
    return { publisherId: publisher.id, keyId: publisher.keyId as string, publicKeyBase64: data.publicKey }
  } finally { await file.close() }
}
