import process from "node:process"
import { clearInterval, setInterval as startInterval } from "node:timers"

import { onCleanup } from "solid-js"

import { createCliAutomationProcessComposition } from "./cli-automation-process-composition.js"
import { createCliBackgroundRuntimeComposition } from "./cli-background-runtime-composition.js"

type AnyFn = (...args: any[]) => any

export type CliAppProcessRuntimeCompositionDeps = Record<string, any> & {
  appLogger: any
  formatError: AnyFn
  flashFooter: AnyFn
  handleSigint: AnyFn
  handleStdinData: AnyFn
}

export function createCliAppProcessRuntimeComposition(
  deps: CliAppProcessRuntimeCompositionDeps,
) {
  const automationProcessComposition = createCliAutomationProcessComposition({
    client: deps.client,
    options: deps.options,
    appLogger: (deps.appLogger ?? null) as any,
    formatError: deps.formatError,
    flashFooter: deps.flashFooter,
    handleSigint: deps.handleSigint,
    handleStdinData: deps.handleStdinData,
    onSigint: (handler) => process.on("SIGINT", handler),
    offSigint: (handler) => process.off("SIGINT", handler),
    onStdinData: (handler) => process.stdin.on("data", handler),
    offStdinData: (handler) => process.stdin.off("data", handler),
    clearTerminalOutputRecordTimer: deps.clearTerminalOutputRecordTimer,
    workspaceScreenMode: deps.workspaceScreenMode,
    workflowScreenActive: deps.workflowScreenActive,
    daemonDisconnected: deps.daemonDisconnected,
    statusLine: deps.statusLine,
    sessionState: deps.sessionState,
    focusedAgentId: deps.focusedAgentId,
    agentActivityLabels: deps.agentActivityLabels,
    streamingAgentId: deps.streamingAgentId,
    agentBusyLatch: deps.agentBusyLatch,
    isAttached: deps.isAttached,
    waitingRoomState: deps.waitingRoomState,
    setWaitingRoomState: deps.setWaitingRoomState,
    availableSessions: deps.availableSessions,
    waitingRoomProjects: deps.waitingRoomProjects,
    applyWaitingRoomSessionLifecycleAction: deps.applyWaitingRoomSessionLifecycleAction,
    restoreWaitingRoomProject: deps.restoreWaitingRoomProject,
    renameWaitingRoomProject: deps.renameWaitingRoomProject,
    providerCatalogState: deps.providerCatalogState,
    waitingRoomCloudNotice: deps.waitingRoomCloudNotice,
    waitingRoomInventoryStatus: deps.waitingRoomInventoryStatus,
    relayStatusState: deps.relayStatusState,
    remoteMachinesState: deps.remoteMachinesState,
    remoteKernelsState: deps.remoteKernelsState,
    terminalsState: deps.terminalsState,
    externalProviderSessionsState: deps.externalProviderSessionsState,
    externalProviderSessionsPageState: deps.externalProviderSessionsPageState,
    slicesState: deps.slicesState,
    providerAccountsState: deps.providerAccountsState,
    waitingRoomTargets: deps.waitingRoomTargets,
    themeRegistryState: deps.themeRegistryState,
    selectedWorkflowId: deps.selectedWorkflowId,
    selectedWorkflowNodeId: deps.selectedWorkflowNodeId,
    workspaceShellContext: deps.workspaceShellContext,
    workspaceShellEntries: deps.workspaceShellEntries,
    transcriptEntries: deps.transcriptEntries,
    visibleTranscriptAgentId: deps.visibleTranscriptAgentId,
    agentPaneEntries: deps.agentPaneEntries,
    queuedPromptStripItemsForAgent: deps.queuedPromptStripItemsForAgent,
    selectedQueuedPromptIndexForAgent: deps.selectedQueuedPromptIndexForAgent,
    footerFlash: deps.footerFlash,
    getInteractionChoiceSelection: deps.getInteractionChoiceSelection,
    getInteractionCustomReply: deps.getInteractionCustomReply,
    isInteractionCustomEditing: deps.isInteractionCustomEditing,
    setInteractionCustomReply: deps.setInteractionCustomReply,
    setInteractionCustomEditing: deps.setInteractionCustomEditing,
    kernelConnected: deps.kernelConnected,
    setWorkspaceScreenMode: deps.setWorkspaceScreenMode,
    rebuildTranscript: deps.rebuildTranscript,
    applyResponseLayout: deps.applyResponseLayout,
    showWorkflowScreen: deps.showWorkflowScreen,
    submitWorkspaceShellCommand: deps.submitWorkspaceShellCommand,
    attachmentState: deps.attachmentState,
    setPromptText: deps.setPromptText,
    submitPrompt: deps.submitPrompt,
    activateWaitingRoom: deps.activateWaitingRoom,
    requestWaitingRoom: deps.requestWaitingRoom,
    connectDetachedKernelFromWaitingRoom: deps.connectDetachedKernelFromWaitingRoom,
    refreshWaitingRoomData: deps.refreshWaitingRoomData,
    submitFocusedInteractionChoice: deps.submitFocusedInteractionChoice,
    cycleFocusedInteractionChoice: deps.cycleFocusedInteractionChoice,
    toggleTurn: deps.toggleTurn,
    toggleAgentPaneTurn: deps.toggleAgentPaneTurn,
    toggleBlob: deps.toggleBlob,
    toggleAgentPaneBlob: deps.toggleAgentPaneBlob,
    onQueuedPromptAction: deps.onQueuedPromptAction,
    restoreTerminalAndExit: deps.restoreTerminalAndExit,
    sleep: deps.sleep,
  })
  automationProcessComposition.start()
  onCleanup(automationProcessComposition.stop)

  return createCliBackgroundRuntimeComposition({
    client: deps.client,
    appLogger: deps.appLogger,
    formatError: deps.formatError,
    sleep: deps.sleep,
    scheduleInterval: startInterval,
    clearInterval,
    closingStateController: deps.closingStateController,
    isAttached: deps.isAttached,
    sessionState: deps.sessionState,
    workflowScreenActive: deps.workflowScreenActive,
    resizeSession: deps.resizeSession,
    setDaemonDisconnected: deps.setDaemonDisconnected,
    setStatusLine: deps.setStatusLine,
    updateSessionChrome: deps.updateSessionChrome,
    appendNotice: deps.appendNotice,
    working: deps.working,
    supportsKernelEventStream: deps.supportsKernelEventStream,
    recoverProviderRun: deps.recoverProviderRun,
    daemonDisconnected: deps.daemonDisconnected,
    recordTurnActivity: deps.recordTurnActivity,
    resolveTerminalRecordAgentId: deps.resolveTerminalRecordAgentId,
    setStreamingAgentId: deps.setStreamingAgentId,
    markAgentBusy: deps.markAgentBusy,
    splitAgentResponseMode: deps.splitAgentResponseMode,
    visibleTranscriptAgentId: deps.visibleTranscriptAgentId,
    focusedAgentId: deps.focusedAgentId,
    hasTrailingUserPrompt: deps.hasTrailingUserPrompt,
    currentAgentPaneEntries: deps.currentAgentPaneEntries,
    appendTranscriptEntryToAgentPane: deps.appendTranscriptEntryToAgentPane,
    appendProviderChunkToAgentPane: deps.appendProviderChunkToAgentPane,
    appendToolUpdateToAgentPane: deps.appendToolUpdateToAgentPane,
    setAgentActivityLabel: deps.setAgentActivityLabel,
    agentActivityLabel: deps.agentActivityLabel,
    setProviderActivityLabel: deps.setProviderActivityLabel,
    applyProviderActivity: deps.applyProviderActivity,
    syncVisibleActivityLabel: deps.syncVisibleActivityLabel,
    appendEntry: deps.appendEntry,
    appendProviderChunk: deps.appendProviderChunk,
    appendToolUpdate: deps.appendToolUpdate,
    appendProviderError: deps.appendProviderError,
    syncVisibleTranscriptPreview: deps.syncVisibleTranscriptPreview,
    appendAgentPanePreview: deps.appendAgentPanePreview,
    markAssistantMessageCompleted: deps.markAssistantMessageCompleted,
    providerRunState: deps.providerRunState,
    shouldRefreshAgentPanesForSessionChange: deps.shouldRefreshAgentPanesForSessionChange,
    applySessionState: deps.applySessionState,
    logProviderRunDebug: deps.logProviderRunDebug,
    setProviderRunState: deps.setProviderRunState,
    refreshAgentPanes: deps.refreshAgentPanes,
    refreshAgentHistories: deps.refreshAgentHistories,
    attachmentState: deps.attachmentState,
    catchUpAttachedSession: deps.catchUpAttachedSession,
    getSessionState: deps.getSessionState,
    getWorkspaceLiveSyncStatus: deps.getWorkspaceLiveSyncStatus,
    setWorkspaceLiveSyncStatus: deps.setWorkspaceLiveSyncStatus,
    tryGetProviderRun: deps.tryGetProviderRun,
    clearLocalBusyStateForAuthoritativeIdle: deps.clearLocalBusyStateForAuthoritativeIdle,
    attachToSession: deps.attachToSession,
    setAttachmentState: deps.setAttachmentState,
    kernelEventSubscriptionController: deps.kernelEventSubscriptionController,
    syncKernelEventSubscription: deps.syncKernelEventSubscription,
    transitionToNoSession: deps.transitionToNoSession,
    queueTerminalOutputRecords: deps.queueTerminalOutputRecords,
    drainTerminalOutputRecords: deps.drainTerminalOutputRecords,
    scheduleSharedPromptInputHistoryRefresh: deps.scheduleSharedPromptInputHistoryRefresh,
    handleWaitingRoomRefresh: deps.handleWaitingRoomRefresh,
    applyWaitingRoomRowsChanged: deps.applyWaitingRoomRowsChanged,
    applyRelayStatusChanged: deps.applyRelayStatusChanged,
    applyRemoteMachinesChanged: deps.applyRemoteMachinesChanged,
    applyProviderCatalogChanged: deps.applyProviderCatalogChanged,
    applySlicesChanged: deps.applySlicesChanged,
    flashFooter: deps.flashFooter,
    recoverAttachedSessionAfterKernelRestart: deps.recoverAttachedSessionAfterKernelRestart,
    setFatalError: deps.setFatalError,
    pumpTerminalOutput: deps.pumpTerminalOutput,
    pollRuntimeNotices: deps.pollRuntimeNotices,
    promptInputRefController: deps.promptInputRefController,
    transcriptScrollboxRefController: deps.transcriptScrollboxRefController,
    primaryTranscriptRuntimeStore: deps.primaryTranscriptRuntimeStore,
    rebuildTranscript: deps.rebuildTranscript,
    syncPromptPlaceholder: deps.syncPromptPlaceholder,
    addResizeListener: (handler) => {
      process.stdout.on("resize", handler)
    },
    removeResizeListener: (handler) => {
      process.stdout.off("resize", handler)
    },
    logViewDebug: deps.logViewDebug,
    footerFlashController: deps.footerFlashController,
    clearPendingPromptDraftPersist: deps.clearPendingPromptDraftPersist,
    cancelPendingTurnCompletion: deps.cancelPendingTurnCompletion,
    sessionChromeUpdateController: deps.sessionChromeUpdateController,
    promptInputHistoryRefreshController: deps.promptInputHistoryRefreshController,
    transcriptHistoryAutoloadController: deps.transcriptHistoryAutoloadController,
    setWorkingAnimationFrame: deps.setWorkingAnimationFrame,
    sessionStatusMode: deps.sessionStatusMode,
    renderSplitPaneFooters: deps.renderSplitPaneFooters,
    waitingRoomState: deps.waitingRoomState,
    setWaitingRoomState: deps.setWaitingRoomState,
    kernelConnected: deps.kernelConnected,
    hydrateCurrentAttachedSession: deps.hydrateCurrentAttachedSession,
  })
}
