import type { CommandNode } from "./command-center-tree-projection.js"

export const COMMAND_TREE: CommandNode[] = [
  {
    id: "session",
    label: "/session",
    description: "Create, attach, list, or delete sessions",
    value: "/session ",
    children: [
      { id: "session-new", label: "new", description: "Create and attach a new session, optionally in a directory/worktree", value: "/session new " },
      { id: "session-attach", label: "attach", description: "Attach to an existing session", value: "/session attach " },
      { id: "session-list", label: "list", description: "List available sessions", value: "/session list" },
      { id: "session-delete", label: "delete", description: "Delete the current or referenced session", value: "/session delete " },
    ],
  },
  {
    id: "agent",
    label: "/agent",
    description: "Manage agents in the current session",
    value: "/agent ",
    children: [
      {
        id: "agent-spawn",
        label: "spawn",
        description: "Spawn local, remote, or slice agents, optionally in a directory/worktree",
        value: "/agent spawn ",
      },
      { id: "agent-delete", label: "delete", description: "Delete the focused or named agent", value: "/agent delete " },
      { id: "agent-destroy", label: "destroy", description: "Alias for /agent delete", value: "/agent destroy " },
      { id: "agent-focus", label: "focus", description: "Focus on a specific agent", value: "/agent focus " },
      { id: "agent-alias", label: "alias", description: "Set or clear an agent alias", value: "/agent alias " },
      { id: "agent-provider", label: "provider", description: "Set the focused or named agent provider", value: "/agent provider " },
      { id: "agent-model", label: "model", description: "Set the focused or named agent model", value: "/agent model " },
      { id: "agent-variant", label: "variant", description: "Set or clear the focused or named agent variant", value: "/agent variant " },
      { id: "agent-list", label: "list", description: "List all agents in the session", value: "/agent list" },
      { id: "agent-cycle", label: "cycle", description: "Cycle to next agent", value: "/agent cycle" },
      {
        id: "agent-substitute",
        label: "substitute",
        description: "Manage fallback provider profiles for the focused agent",
        value: "/agent substitute ",
        children: [
          { id: "agent-substitute-list", label: "list", description: "List agent substitutes", value: "/agent substitute list" },
          { id: "agent-substitute-add", label: "add", description: "Add a substitute provider/model", value: "/agent substitute add " },
          { id: "agent-substitute-activate", label: "activate", description: "Manually activate a substitute", value: "/agent substitute activate " },
          { id: "agent-substitute-primary", label: "primary", description: "Return to primary provider profile", value: "/agent substitute primary" },
        ],
      },
    ],
  },
  {
    id: "cloud",
    label: "/cloud",
    description: "Open Arroba Cloud and manage collaboration",
    value: "/cloud ",
    children: [
      { id: "cloud-open", label: "open", description: "Open the Arroba Cloud browser terminal", value: "/cloud open" },
      { id: "cloud-link", label: "link", description: "Pair this machine with Arroba Cloud", value: "/cloud link" },
      { id: "cloud-status", label: "status", description: "Show Cloud pairing and relay status", value: "/cloud status" },
      { id: "cloud-invite-create", label: "invite create", description: "Create a cloud-backed session invite with a collaboration level", value: "/cloud invite create --level " },
      { id: "cloud-invite-accept", label: "invite accept", description: "Accept a cloud-backed session invite", value: "/cloud invite accept " },
      { id: "cloud-members", label: "members", description: "List cloud members for the current session", value: "/cloud members" },
      { id: "cloud-collaborators", label: "collaborators", description: "List recent cloud collaborators", value: "/cloud collaborators" },
    ],
  },
  {
    id: "relay",
    label: "/relay",
    description: "Manage relay connection and self-hosted collaboration",
    value: "/relay ",
    children: [
      { id: "relay-status", label: "status", description: "Show relay configuration and connection status", value: "/relay status" },
      { id: "relay-use", label: "use", description: "Configure a self-hosted relay URL and token", value: "/relay use " },
      { id: "relay-disable", label: "disable", description: "Disable relay configuration", value: "/relay disable" },
      { id: "relay-invite-create", label: "invite create", description: "Create a same-relay session invite with a collaboration level", value: "/relay invite create --level " },
      { id: "relay-invite-accept", label: "invite accept", description: "Accept a same-relay session invite", value: "/relay invite accept " },
      { id: "relay-members", label: "members", description: "List same-relay members for the current session", value: "/relay members" },
    ],
  },
  {
    id: "collab",
    label: "/collab",
    description: "Manage collaboration using the configured backend",
    value: "/collab ",
    children: [
      { id: "collab-invite-create", label: "invite create", description: "Create a collaboration invite with a collaboration level", value: "/collab invite create --level " },
      { id: "collab-invite-accept", label: "invite accept", description: "Accept a collaboration invite", value: "/collab invite accept " },
      { id: "collab-members", label: "members", description: "List members for the current session", value: "/collab members" },
      { id: "collab-invites", label: "invites", description: "List active collaboration invites", value: "/collab invites" },
    ],
  },
  {
    id: "kernel",
    label: "/kernel",
    description: "Inspect or delete the active kernel",
    value: "/kernel ",
    children: [
      { id: "kernel-health", label: "health", description: "Show runtime health and provider-run invariants", value: "/kernel health" },
      { id: "kernel-delete", label: "delete", description: "Delete this kernel and its sessions", value: "/kernel delete" },
    ],
  },
  {
    id: "mcp",
    label: "/mcp",
    description: "Manage Arroba MCP registry and agent grants",
    value: "/mcp ",
    children: [
      { id: "mcp-list", label: "list", description: "List Arroba-managed MCPs", value: "/mcp list" },
      { id: "mcp-install", label: "install", description: "Install an MCP into Arroba", value: "/mcp install " },
      { id: "mcp-import", label: "import", description: "Import provider MCPs into Arroba", value: "/mcp import " },
      { id: "mcp-grant", label: "grant", description: "Grant an MCP to an agent", value: "/mcp grant " },
      { id: "mcp-revoke", label: "revoke", description: "Revoke an MCP from an agent", value: "/mcp revoke " },
      { id: "mcp-grants", label: "grants", description: "Show an agent's MCP grants", value: "/mcp grants " },
      { id: "mcp-show", label: "show", description: "Show MCP config", value: "/mcp show " },
    ],
  },
  {
    id: "skill",
    label: "/skill",
    description: "Manage Arroba skills and agent grants",
    value: "/skill ",
    children: [
      { id: "skill-list", label: "list", description: "List Arroba-managed skills", value: "/skill list" },
      { id: "skill-install", label: "install", description: "Install a skill into Arroba", value: "/skill install " },
      { id: "skill-import", label: "import", description: "Import provider skills into Arroba", value: "/skill import " },
      { id: "skill-grant", label: "grant", description: "Grant a skill to an agent", value: "/skill grant " },
      { id: "skill-revoke", label: "revoke", description: "Revoke a skill from an agent", value: "/skill revoke " },
      { id: "skill-grants", label: "grants", description: "Show an agent's skill grants", value: "/skill grants " },
      { id: "skill-show", label: "show", description: "Show skill metadata", value: "/skill show " },
    ],
  },
  {
    id: "env",
    label: "/env",
    description: "Manage external script environments",
    value: "/env ",
    children: [
      { id: "env-list", label: "list", description: "List script environments", value: "/env list" },
      { id: "env-register", label: "register", description: "Register Python or Node environment", value: "/env register " },
      { id: "env-remove", label: "remove", description: "Remove an environment", value: "/env remove " },
      { id: "env-show", label: "show", description: "Show environment config", value: "/env show " },
    ],
  },
  {
    id: "script",
    label: "/script",
    description: "Manage script extensions",
    value: "/script ",
    children: [
      { id: "script-list", label: "list", description: "List script extensions", value: "/script list" },
      { id: "script-validate", label: "validate", description: "Validate a script with test_run", value: "/script validate " },
      { id: "script-register", label: "register", description: "Register a script extension", value: "/script register " },
      { id: "script-grant", label: "grant", description: "Grant a script to an agent", value: "/script grant " },
      { id: "script-revoke", label: "revoke", description: "Revoke a script from an agent", value: "/script revoke " },
      { id: "script-grants", label: "grants", description: "Show an agent's script grants", value: "/script grants " },
      { id: "script-show", label: "show", description: "Show script metadata", value: "/script show " },
    ],
  },
  {
    id: "credential",
    label: "/credential",
    description: "Manage connector credentials",
    value: "/credential ",
    children: [
      { id: "credential-list", label: "list", description: "List credentials", value: "/credential list" },
      { id: "credential-set", label: "set", description: "Store a vault secret", value: "/credential set " },
      { id: "credential-register", label: "register", description: "Register credential YAML", value: "/credential register " },
      { id: "credential-remove", label: "remove", description: "Remove a credential", value: "/credential remove " },
      { id: "credential-show", label: "show", description: "Show credential metadata", value: "/credential show " },
    ],
  },
  {
    id: "connector",
    label: "/connector",
    description: "Manage API connector extensions",
    value: "/connector ",
    children: [
      { id: "connector-list", label: "list", description: "List connectors", value: "/connector list" },
      { id: "connector-register", label: "register", description: "Register connector YAML", value: "/connector register " },
      { id: "connector-doctor", label: "doctor", description: "Check connector metadata and credential policy", value: "/connector doctor " },
      { id: "connector-test", label: "test", description: "Test a connector operation", value: "/connector test " },
      { id: "connector-grant", label: "grant", description: "Grant a connector to an agent", value: "/connector grant " },
      { id: "connector-revoke", label: "revoke", description: "Revoke a connector from an agent", value: "/connector revoke " },
      { id: "connector-grants", label: "grants", description: "Show connector grants", value: "/connector grants " },
      { id: "connector-show", label: "show", description: "Show connector metadata", value: "/connector show " },
    ],
  },
  {
    id: "extension",
    label: "/extension",
    description: "Grant or revoke any extension kind",
    value: "/extension ",
    children: [
      { id: "extension-grant", label: "grant", description: "Grant an extension to an agent", value: "/extension grant " },
      { id: "extension-revoke", label: "revoke", description: "Revoke an extension from an agent", value: "/extension revoke " },
      { id: "extension-grants", label: "grants", description: "Show extension grants", value: "/extension grants " },
      { id: "extension-sync-status", label: "sync-status", description: "Show remote extension manifest sync", value: "/extension sync-status " },
      { id: "extension-sync-retry", label: "sync-retry", description: "Retry remote extension manifest sync", value: "/extension sync-retry " },
      { id: "extension-audit", label: "audit", description: "Show home extension audit events", value: "/extension audit " },
    ],
  },
  {
    id: "workflow",
    label: "/workflow",
    description: "Inspect, edit, and run workflows",
    value: "/workflow ",
    children: [
      { id: "workflow-open", label: "open", description: "Open the workflow outline", value: "/workflow" },
      { id: "workflow-list", label: "list", description: "List workflows in the workspace", value: "/workflow list" },
      { id: "workflow-show", label: "show", description: "Show a workflow by id or alias", value: "/workflow show " },
      { id: "workflow-new", label: "new", description: "Create a new workflow", value: "/workflow new " },
      { id: "workflow-run", label: "run", description: "Invoke a workflow endpoint", value: "/workflow run " },
      { id: "workflow-start", label: "start", description: "Alias for /workflow run", value: "/workflow start " },
      { id: "workflow-flush-context", label: "flush-context", description: "Set whether workflow runs start with fresh provider sessions", value: "/workflow flush-context " },
      { id: "workflow-run-output-schema", label: "run-output-schema", description: "Set the workflow final output schema", value: "/workflow run-output-schema " },
      { id: "workflow-max-turns", label: "max-turns", description: "Set max workflow turns across all agents", value: "/workflow max-turns " },
      { id: "workflow-runs", label: "runs", description: "List workflow runs in the session", value: "/workflow runs " },
      { id: "workflow-add-node-all", label: "add node all", description: "Add every session agent that is not already a workflow node", value: "/workflow add node all" },
      {
        id: "workflow-queue",
        label: "queue",
        description: "Inspect and manage workflow prompt queues",
        value: "/workflow queue ",
        children: [
          { id: "workflow-queue-list", label: "list", description: "List workflow prompt queues and queued prompts", value: "/workflow queue" },
          { id: "workflow-queue-create", label: "create", description: "Create a workflow prompt queue", value: "/workflow queue create " },
          { id: "workflow-queue-edit", label: "edit", description: "Edit a queued workflow prompt", value: "/workflow queue edit " },
          { id: "workflow-queue-move", label: "move", description: "Move a queued prompt to another queue", value: "/workflow queue move " },
          { id: "workflow-queue-clear", label: "clear", description: "Clear a workflow prompt queue", value: "/workflow queue clear " },
          { id: "workflow-queue-remove", label: "remove", description: "Remove one queued workflow prompt", value: "/workflow queue remove " },
        ],
      },
      { id: "workflow-cancel", label: "cancel", description: "Cancel a workflow run", value: "/workflow cancel " },
      { id: "workflow-resume", label: "resume", description: "Resume a stopped workflow run", value: "/workflow resume " },
      {
        id: "workflow-pane",
        label: "pane",
        description: "Switch workflow detail pane",
        value: "/workflow pane ",
        children: [
          { id: "workflow-pane-logs", label: "logs", description: "Show workflow logs", value: "/workflow pane logs " },
          { id: "workflow-pane-trace", label: "trace", description: "Show selected agent trace", value: "/workflow pane trace " },
          { id: "workflow-pane-edit", label: "edit", description: "Show workflow component editor", value: "/workflow pane edit " },
        ],
      },
      {
        id: "workflow-watchdog",
        label: "watchdog",
        description: "Manage scheduled endpoint triggers",
        value: "/workflow watchdog ",
        children: [
          { id: "workflow-watchdog-add", label: "add", description: "Create a scheduled endpoint trigger", value: "/workflow watchdog add " },
          { id: "workflow-watchdog-list", label: "list", description: "List workflow watchdogs", value: "/workflow watchdog list " },
          { id: "workflow-watchdog-enable", label: "enable", description: "Enable a watchdog", value: "/workflow watchdog enable " },
          { id: "workflow-watchdog-disable", label: "disable", description: "Disable a watchdog", value: "/workflow watchdog disable " },
          { id: "workflow-watchdog-remove", label: "remove", description: "Remove a watchdog", value: "/workflow watchdog remove " },
        ],
      },
      { id: "workflow-alias", label: "alias", description: "Assign an alias to an existing workflow", value: "/workflow " },
      {
        id: "workflow-node",
        label: "node",
        description: "Manage workflow nodes",
        value: "/workflow node ",
        children: [
          { id: "workflow-node-add", label: "add", description: "Add a workflow node for an agent", value: "/workflow node add " },
          { id: "workflow-node-add-all", label: "add all", description: "Add every session agent that is not already a workflow node", value: "/workflow node add all" },
          { id: "workflow-node-remove", label: "remove", description: "Remove a workflow node", value: "/workflow node remove " },
          { id: "workflow-node-can-complete-run", label: "can-complete-run", description: "Allow a node to complete the workflow run", value: "/workflow node can-complete-run " },
          { id: "workflow-node-max-turns", label: "max-turns", description: "Set the node turn budget for one workflow run", value: "/workflow node max-turns " },
          {
            id: "workflow-node-instructions",
            label: "instructions",
            description: "Manage workflow node instructions",
            value: "/workflow node instructions ",
            children: [
              { id: "workflow-node-instructions-show", label: "show", description: "Show workflow node instructions in the I/O panel", value: "/workflow node instructions show " },
              { id: "workflow-node-instructions-set", label: "set", description: "Set workflow node instructions (optional file)", value: "/workflow node instructions set " },
              { id: "workflow-node-instructions-save", label: "save", description: "Save the current workflow node instructions draft", value: "/workflow node instructions save" },
              { id: "workflow-node-instructions-close", label: "close", description: "Close the workflow node instructions panel", value: "/workflow node instructions close" },
            ],
          },
        ],
      },
      {
        id: "workflow-edge",
        label: "edge",
        description: "Manage workflow edges",
        value: "/workflow edge ",
        children: [
          { id: "workflow-edge-shorthand", label: "connect", description: "Add a directed edge between two workflow nodes", value: "/workflow " },
          { id: "workflow-edge-add", label: "add", description: "Add a directed edge between workflow nodes", value: "/workflow edge add " },
          { id: "workflow-edge-remove", label: "remove", description: "Remove a workflow edge", value: "/workflow edge remove " },
        ],
      },
      {
        id: "workflow-endpoint",
        label: "endpoint",
        description: "Manage workflow endpoints",
        value: "/workflow endpoint ",
        children: [
          { id: "workflow-endpoint-new", label: "new", description: "Create a workflow endpoint", value: "/workflow endpoint new " },
          { id: "workflow-endpoint-alias", label: "alias", description: "Assign an alias to a workflow endpoint", value: "/workflow endpoint alias " },
          { id: "workflow-endpoint-bind", label: "bind", description: "Bind an endpoint to a workflow node", value: "/workflow endpoint bind " },
        ],
      },
    ],
  },
  {
    id: "slice",
    label: "/slice",
    description: "Manage kernel-owned slices",
    value: "/slice ",
    children: [
      { id: "slice-list", label: "list", description: "List slices owned by this kernel", value: "/slice list" },
      { id: "slice-create", label: "create", description: "Create a slice inventory entry", value: "/slice create " },
      { id: "slice-status", label: "status", description: "Show a slice", value: "/slice status " },
      { id: "slice-start", label: "start", description: "Start a slice", value: "/slice start " },
      { id: "slice-stop", label: "stop", description: "Stop a slice", value: "/slice stop " },
      { id: "slice-delete", label: "delete", description: "Delete a slice", value: "/slice delete " },
      { id: "slice-screen", label: "screen", description: "Open or show the slice screen URL", value: "/slice screen " },
      { id: "slice-auth-import", label: "auth import", description: "Import host provider auth into a slice", value: "/slice auth import " },
      { id: "slice-auth-remove", label: "auth remove", description: "Remove provider auth from a slice", value: "/slice auth remove " },
      { id: "slice-auth-login", label: "auth login", description: "Start provider login inside a slice", value: "/slice auth login " },
      { id: "slice-auth-alias", label: "auth alias", description: "Set or clear a provider account alias", value: "/slice auth alias " },
    ],
  },
  {
    id: "workspace",
    label: "/workspace",
    description: "Set workspace paths, links, and live sync status",
    value: "/workspace ",
    children: [
      { id: "workspace-set", label: "set", description: "Set the next-session workspace path", value: "/workspace " },
      { id: "workspace-link-create", label: "link create", description: "Create a session workspace link", value: "/workspace link create " },
      { id: "workspace-link-list", label: "link list", description: "List session workspace links", value: "/workspace link list" },
      { id: "workspace-link-show", label: "link show", description: "Show workspace link attachments", value: "/workspace link show " },
      { id: "workspace-link-attach", label: "link attach", description: "Attach the current worktree to a link", value: "/workspace link attach " },
      { id: "workspace-link-detach", label: "link detach", description: "Detach the current worktree from a link", value: "/workspace link detach " },
      { id: "workspace-sync-status", label: "sync status", description: "Show workspace live sync status and ignore rules", value: "/workspace sync status" },
      { id: "workspace-sync-targets", label: "sync targets", description: "List workspace live sync targets", value: "/workspace sync targets" },
      { id: "workspace-sync-conflicts", label: "sync conflicts", description: "List workspace live sync conflicts", value: "/workspace sync conflicts" },
      { id: "workspace-sync-ignore", label: "sync ignore", description: "Show workspace live sync ignore rules", value: "/workspace sync ignore" },
      { id: "workspace-sync-off", label: "sync off", description: "Disable workspace live sync", value: "/workspace sync off" },
      { id: "workspace-sync-managed", label: "sync managed", description: "Use managed workspace live sync", value: "/workspace sync managed" },
      { id: "workspace-sync-tracked", label: "sync tracked", description: "Use tracked workspace live sync", value: "/workspace sync tracked" },
      { id: "workspace-sync-enable-managed", label: "sync enable managed", description: "Enable managed workspace live sync", value: "/workspace sync enable managed" },
      { id: "workspace-sync-enable-tracked", label: "sync enable tracked", description: "Enable tracked workspace live sync", value: "/workspace sync enable tracked" },
      { id: "workspace-sync-disable", label: "sync disable", description: "Disable workspace live sync", value: "/workspace sync disable" },
      {
        id: "workspace-sync-mode",
        label: "sync mode",
        description: "Set workspace live sync mode",
        value: "/workspace sync mode ",
        children: [
          {
            id: "workspace-sync-mode-managed",
            label: "managed",
            description: "Sync Arroba-managed writes with collision checks",
            value: "/workspace sync mode managed",
          },
          {
            id: "workspace-sync-mode-tracked",
            label: "tracked",
            description: "Sync Arroba-turn file changes without write enforcement",
            value: "/workspace sync mode tracked",
          },
          {
            id: "workspace-sync-mode-off",
            label: "off",
            description: "Disable workspace live sync for this session",
            value: "/workspace sync mode off",
          },
        ],
      },
      { id: "workspace-sync-link", label: "sync link", description: "Attach this worktree to a sync link", value: "/workspace sync link " },
    ],
  },
  {
    id: "worktree",
    label: "/worktree",
    description: "Set, create, or name the next-session worktree",
    value: "/worktree ",
    children: [
      { id: "worktree-set", label: "set", description: "Set the next-session worktree path", value: "/worktree " },
      { id: "worktree-create", label: "create", description: "Create a new git worktree for a branch", value: "/worktree create " },
      { id: "worktree-name", label: "name", description: "Assign a user-facing alias to the selected worktree", value: "/worktree name " },
    ],
  },
  {
    id: "provider",
    label: "/provider",
    description: "Change provider and manage auth",
    value: "/provider ",
    children: [
      { id: "provider-select", label: "switch", description: "Choose the active provider", value: "/provider " },
      { id: "provider-status", label: "status", description: "Show provider auth status", value: "/provider status " },
      { id: "provider-login", label: "login", description: "Start provider login", value: "/provider login " },
      { id: "provider-logout", label: "logout", description: "Log out a provider", value: "/provider logout " },
      { id: "provider-reauth", label: "reauth", description: "Reauthenticate a provider", value: "/provider reauth " },
      {
        id: "provider-processes",
        label: "processes",
        description: "List daemon-tracked provider processes or safely tear them down",
        value: "/provider processes ",
      },
    ],
  },
  {
    id: "config",
    label: "/config",
    description: "Inspect and update Arroba user config",
    value: "/config ",
    children: [
      { id: "config-show", label: "show", description: "Show the effective Arroba user config", value: "/config show" },
      { id: "config-path", label: "path", description: "Show the Arroba user config path", value: "/config path" },
      { id: "config-keys", label: "keys", description: "List settable Arroba user config keys", value: "/config keys" },
      { id: "config-schema", label: "schema", description: "Show Arroba user config key metadata", value: "/config schema" },
      { id: "config-set", label: "set", description: "Set a dotted config key", value: "/config set " },
      { id: "config-unset", label: "unset", description: "Unset a dotted config key", value: "/config unset " },
      {
        id: "config-workspace-live-sync",
        label: "workspace-live-sync",
        description: "Set the global workspace live sync policy",
        value: "/config workspace-live-sync ",
        children: [
          {
            id: "config-workspace-live-sync-off",
            label: "off",
            description: "Disable workspace live sync by default",
            value: "/config workspace-live-sync off",
          },
          {
            id: "config-workspace-live-sync-managed",
            label: "managed",
            description: "Enable managed workspace live sync for supported provider runs",
            value: "/config workspace-live-sync managed",
          },
          {
            id: "config-workspace-live-sync-tracked",
            label: "tracked",
            description: "Enable tracked workspace live sync for supported provider runs",
            value: "/config workspace-live-sync tracked",
          },
        ],
      },
    ],
  },
  {
    id: "model",
    label: "/model",
    description: "Change the active model",
    value: "/model ",
  },
  {
    id: "variant",
    label: "/variant",
    description: "Change the active model variant",
    value: "/variant ",
  },
  {
    id: "view",
    label: "/view",
    description: "Change multi-agent response layout",
    value: "/view ",
    children: [
      { id: "view-individual", label: "individual", description: "Show one focused agent transcript at a time", value: "/view individual" },
      { id: "view-split", label: "split", description: "Split the response area across active session agents", value: "/view split" },
    ],
  },
  {
    id: "misc",
    label: "/misc",
    description: "Attachments, control, and app commands",
    value: "/",
    children: [
      { id: "attach", label: "/attach", description: "Attach files or screenshots to the prompt", value: "/attach " },
      { id: "stop", label: "/stop", description: "Stop the active provider turn", value: "/stop" },
      { id: "waiting", label: "/waiting", description: "Go to the waiting room", value: "/waiting" },
      { id: "exit", label: "/exit", description: "Leave the CLI", value: "/exit" },
    ],
  },
]
