import assert from "node:assert/strict"
import test from "node:test"

import type { DaemonHealthProjection } from "@arroba/kernel-client"
import {
  formatKernelHealth,
  formatKernelRemoteRuntimeHealth,
  handleKernelSlashCommand,
  kernelHealthIssueCount,
  kernelRemoteRuntimeIssueCount,
  kernelRemoteRuntimeReadiness,
} from "./kernel-command-handlers.js"
import { makeSession } from "./command-actions-test-support.js"

export {
  assert,
  formatKernelHealth,
  formatKernelRemoteRuntimeHealth,
  handleKernelSlashCommand,
  kernelHealthIssueCount,
  kernelRemoteRuntimeIssueCount,
  kernelRemoteRuntimeReadiness,
  makeSession,
  test,
}

export function health(overrides: Partial<DaemonHealthProjection> = {}): DaemonHealthProjection {
  return {
    metadata: { projection_version: 1, last_event_id: 7, generated_at_ms: 100 },
    session_command_lanes: [{ lane_id: "session-1", queue_limit: 128, queued_commands: 1 }],
    agent_command_lanes: [{ lane_id: "agent-1", queue_limit: 128, queued_commands: 2 }],
    workflow_command_lanes: [],
    provider_runtime_lanes: [],
    provider_run_actor: { enqueued_commands: 3, enqueue_rejections: 0 },
    process: { process_id: 1234, current_resident_set_bytes: 134217728, peak_resident_set_bytes: 268435456 },
    capability_executor: {
      max_concurrent_jobs: 64,
      available_permits: 64,
      submitted_jobs: 0,
      running_jobs: 0,
      completed_jobs: 0,
      failed_jobs: 0,
      rejected_jobs: 0,
      join_errors: 0,
    },
    session_projection: {
      projected_sessions: 1,
      projected_session_list_entries: 1,
      active_prompts: 0,
      queued_prompts: 0,
    },
    agent_runtime_projection: { projected_agents: 1, active_prompts: 0, queued_prompts: 0 },
    provider_catalog: { cached: false, expired: false, age_ms: null, ttl_ms: 5000 },
    provider_runs: {
      projected_runs: 1,
      active_runs: 1,
      arroba_active_runs: 1,
      native_tui_active_runs: 0,
      terminal_diagnostics: [],
      duplicate_arroba_agent_bindings: [],
      duplicate_native_tui_agent_bindings: [],
      multi_interface_agent_bindings: [],
      orphaned_active_runs: [],
      session_active_run_mismatches: [],
    },
    transport: {
      active_connections: 1,
      active_subscriptions: 1,
      retained_event_limit: 256,
      command_result_cache_limit: 512,
      inbound_request_limit: 8,
      incoming_requests: 0,
      emitted_events: 0,
      replay_gaps: 0,
      inbound_overload_rejections: 0,
      duplicate_command_conflicts: 0,
      outgoing_queue_overflows: 0,
      slow_consumer_closes: 0,
      relay_reconnect_attempts: 0,
      relay_last_reconnect_reason: null,
      relay_last_reconnect_delay_ms: null,
      relay_last_reconnect_url: null,
      relay_last_connected_url: null,
    },
    terminal_stream: {
      pending_output_records: 0,
      pending_notice_records: 0,
      pending_completion_records: 0,
      pending_output_record_limit_per_attachment: 4096,
      trimmed_pending_output_recipients: 0,
    },
    slice_lifecycle: {
      total_slices: 0,
      running_slices: 0,
      starting_slices: 0,
      stopping_slices: 0,
      stopped_slices: 0,
      unhealthy_slices: 0,
      attached_agents: 0,
      failed_operations: 0,
      in_progress_operations: 0,
      issues: [],
      provider_auth_missing_slices: 0,
      provider_auth_unconfigured_slices: 0,
      provider_auth_issues: [],
    },
    remote_execution: {
      remote_agents: 0,
      active_remote_agents: 0,
      missing_active_worker_runs: 0,
      malformed_bindings: 0,
      issues: [],
    },
    remote_extension_sync: {
      remote_agents: 0,
      home_proxy_agents: 0,
      home_proxy_grants: 0,
      manifest_missing_agents: 0,
      synced_agents: 0,
      syncing_agents: 0,
      pending_agents: 0,
      failed_agents: 0,
      stale_agents: 0,
      pending_revoke_agents: 0,
      issues: [],
    },
    workspace_coordination: {
      active_worktree_claims: [],
      worktree_collisions: [],
      active_operation_claims: [],
    },
    workspace_live_sync: {
      active_reservations: 0,
      active_reservation_artifacts: 0,
      managed_mode: {
        write_fence_supported: true,
        write_fence_backend: "macos-seatbelt",
        unavailable_reason: null,
      },
      workspace_identity: {
        tracked_provider_runs: 0,
        identity_changed_provider_runs: 0,
        invalid_provider_runs: 0,
        current_generation_total: 0,
        issues: [],
      },
      external_changes: {
        tracked_artifacts: 0,
        externally_changed_artifacts: 0,
        external_change_events: 0,
        live_watcher_started: false,
        live_watcher_scans: 0,
        live_watcher_scan_errors: 0,
        issues: [],
      },
    },
    projection_invariants: { checked_sessions: 1, checked_agents: 1, mismatches: [] },
    ...overrides,
  }
}

