export {
  cursorIsOnFirstPromptLine,
  cursorIsOnLastPromptLine,
  extractPromptHistoryEntries,
  extractPromptInputHistoryEntries,
  isProgrammaticPromptContentEcho,
  maxPromptInputHistorySequence,
  navigatePromptHistory,
  promptHistoryDirectionForKey,
  promptHistoryEntryListsEqual,
  pushPromptHistoryEntry,
  resolvePromptHistoryKeyNavigation,
  type PromptContentChangePolicy,
  type PromptHistoryDirection,
  type PromptHistoryKeyPolicy,
  type PromptHistoryNavigation,
  type PromptHistoryNavigationKeyPolicy,
  type PromptHistoryNavigationResult,
} from "@arroba/kernel-client/prompt-history"
