export {
  cycleWaitingRoomLaunchKernel,
  cycleWaitingRoomLaunchMachine,
  formatWaitingRoomLaunchKernelValue,
  formatWaitingRoomLaunchMachineValue,
  normalizeWaitingRoomLaunchPlacement,
  waitingRoomLaunchKernelOptions,
  waitingRoomLaunchMachineOptions,
  waitingRoomLaunchPlacement,
  waitingRoomSelectedLaunchKernelRef,
  waitingRoomSelectedLaunchMachineRef,
  type WaitingRoomLaunchKernelOption,
  type WaitingRoomLaunchMachineOption,
  type WaitingRoomLaunchPlacementState,
  type WaitingRoomLaunchRemoteState,
} from "@arroba/kernel-client/waiting-room-runtime-placement"
